#!/usr/bin/env python3
"""Regenerate EVERY canopy brand image from the one geometry source.

The mark (the low dome) is defined ONCE in `assets/brand/mark.py`. This script
renders it into every committed image the product needs, so nothing is drawn
just-in-time at build or runtime. Edit `mark.py` to change the shape, then run this
and commit the results — never hand-edit the outputs.

    brew install librsvg                 # one-time: rsvg-convert
    python3 assets/brand/generate.py     # regenerate all

Outputs (all committed, first-class):
    assets/brand/mark.svg                  master vector (green mark on the bark tile)
    assets/brand/menubar-mark.png/@2x/@3x  monochrome mark for the macOS status bar
                                           (the menu-bar app tints it per runner status)
    assets/brand/app-icon-1024.png         macOS app-icon artwork
    assets/brand/AppIcon.icns              compiled macOS app icon (all sizes)
    frontend/public/favicon.svg            web favicon
    frontend/public/icons/icon-*.png       PWA icons (+ maskable)
    frontend/src/brand/CanopyMark.tsx      the mark as a React component (currentColor)
    site/public/favicon.svg, site/src/assets/mark.svg   the public site's copies

Rasters go through `rsvg-convert`, so every PNG is rendered from the same SVG the web
uses rather than from a second drawing of the shape. `.icns` needs macOS `iconutil`;
asset generation is a dev-machine task and CI only reads the committed files.
"""
from __future__ import annotations

import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
BRAND = REPO / "assets" / "brand"
WEB_PUBLIC = REPO / "frontend" / "public"
WEB_COMPONENT = REPO / "frontend" / "src" / "brand" / "CanopyMark.tsx"
SITE = REPO / "site"

sys.path.insert(0, str(BRAND))
import mark  # noqa: E402

# Brand palette (canopy Warm Earth) — the ONLY place these hexes live for the mark.
BARK = "#26211D"   # the tile
GREEN = "#3FA374"  # the mark on the tile
BLACK = "#000000"  # menu-bar template ink (tinted per status at runtime)

# The menu bar is short and the mark is wide, so its image is a landscape box (points).
MENUBAR_PT = (24, 16)


def _rel(path: Path) -> str:
    try:
        return str(path.relative_to(REPO))
    except ValueError:
        return str(path)


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    print(f"  wrote {_rel(path)}")


def _png(svg_text: str, path: Path, width: int, height: int | None = None) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    args = ["rsvg-convert", "-w", str(width), "-h", str(height or width), "-o", str(path)]
    subprocess.run(args, input=svg_text.encode(), check=True)
    print(f"  wrote {_rel(path)}")


def tile(px: int, *, fill: float, radius: float) -> str:
    return mark.svg(px, px, GREEN, fill=fill, background=BARK, radius=radius)


def app_icon(px: int) -> str:
    """The macOS app icon: a rounded tile inset from the canvas edge, as Apple's grid
    expects, with the mark inside it."""
    inset = px * 0.06
    inner = px - 2 * inset
    nested = tile(int(inner), fill=0.70, radius=0.225).replace(
        "<svg ", f'<svg x="{inset:g}" y="{inset:g}" ', 1)
    return (f'<svg xmlns="http://www.w3.org/2000/svg" width="{px}" height="{px}" '
            f'viewBox="0 0 {px} {px}">{nested}</svg>\n')


def component() -> str:
    x0, y0, x1, y1 = mark.bounds()
    pad = 0.5
    vb = f"{x0 - pad:.2f} {y0 - pad:.2f} {x1 - x0 + 2 * pad:.2f} {y1 - y0 + 2 * pad:.2f}"
    return f"""// GENERATED by assets/brand/generate.py from assets/brand/mark.py — do not edit.
// The canopy mark (the low dome), drawn in currentColor so it takes the text colour
// of wherever it sits. Size it with a height class; the width follows its aspect.
import type {{ SVGProps }} from 'react'

export function CanopyMark(props: SVGProps<SVGSVGElement>) {{
  return (
    <svg viewBox="{vb}" role="img" aria-label="Canopy" {{...props}}>
      {mark.body("currentColor").replace('"/>', '" />')}
    </svg>
  )
}}
"""


def main() -> None:
    if not shutil.which("rsvg-convert"):
        raise SystemExit("rsvg-convert not found: brew install librsvg")
    print("Regenerating brand assets from assets/brand/mark.py:")

    master = tile(512, fill=0.70, radius=0.22)
    _write(BRAND / "mark.svg", master)

    favicon = tile(64, fill=0.80, radius=0.22)
    _write(WEB_PUBLIC / "favicon.svg", favicon)
    if SITE.is_dir():  # the public site (site/), when this checkout has one
        _write(SITE / "public" / "favicon.svg", favicon)
        _write(SITE / "src" / "assets" / "mark.svg", mark.svg(116, 46, "currentColor"))
    _write(WEB_COMPONENT, component())

    w, h = MENUBAR_PT
    for scale, suffix in [(1, ""), (2, "@2x"), (3, "@3x")]:
        _png(mark.svg(w, h, BLACK), BRAND / f"menubar-mark{suffix}.png", w * scale, h * scale)

    _png(app_icon(1024), BRAND / "app-icon-1024.png", 1024)
    with tempfile.TemporaryDirectory() as td:
        iconset = Path(td) / "AppIcon.iconset"
        for px, name in [(16, "16x16"), (32, "16x16@2x"), (32, "32x32"), (64, "32x32@2x"),
                         (128, "128x128"), (256, "128x128@2x"), (256, "256x256"),
                         (512, "256x256@2x"), (512, "512x512"), (1024, "512x512@2x")]:
            _png(app_icon(1024), iconset / f"icon_{name}.png", px)
        subprocess.run(["iconutil", "-c", "icns", str(iconset), "-o",
                        str(BRAND / "AppIcon.icns")], check=True)
        print(f"  wrote {_rel(BRAND / 'AppIcon.icns')}")

    # PWA: the OS applies its own mask, so these are full-bleed squares. Maskable keeps
    # the mark inside the 80% safe zone so a circular mask cannot clip the dome's ends.
    for px, name, fill in [(192, "icon-192.png", 0.72), (512, "icon-512.png", 0.72),
                           (512, "icon-maskable-512.png", 0.56)]:
        _png(tile(px, fill=fill, radius=0), WEB_PUBLIC / "icons" / name, px)

    print("Done. Commit the changes under assets/brand/, frontend/ and site/.")


if __name__ == "__main__":
    main()
