# Generated by Django 6.1.1 on 2026-10-04 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent_runs", "0001_initial"),
        ("agents", "0035_agent_delegation"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentrun",
            name="ext_id",
            field=models.CharField(
                blank=True,
                help_text="The workflow's own run id (DDD: <narrative>-YYYY-MM-DD-NNN). Globally unique: walkthroughs and reviews join to the run by this string.",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="holder",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Runner (user@host) that last wrote.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="holder_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="kind",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text='e.g. "ddd".',
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="The agent project this run is work on.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="runs",
                to="agents.agentproject",
            ),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="state",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="The kind's full run-state document.",
            ),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="state_version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="subject",
            field=models.CharField(
                blank=True,
                default="",
                help_text="DDD: the narrative slug.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="summary",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Small kind-defined digest for lists.",
            ),
        ),
        migrations.AddIndex(
            model_name="agentrun",
            index=models.Index(
                fields=["kind", "subject"], name="agent_runs__kind_af5c34_idx"
            ),
        ),
    ]
