# Generated by Django 6.1.1 on 2026-10-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent_runs", "0002_run_documents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentrun",
            name="status",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Mirror of derived status; read model recomputes from steps.",
                max_length=40,
            ),
        ),
    ]
