# Generated by Django 5.2.12 on 2026-07-31 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0006_alter_workspace_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=64)),
                ('kind', models.CharField(max_length=64)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warn', 'Warn'), ('error', 'Error')], default='info', max_length=8)),
                ('key', models.CharField(blank=True, default='', max_length=200)),
                ('summary', models.CharField(blank=True, default='', max_length=500)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('count', models.PositiveIntegerField(default=1)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['workspace', '-last_seen_at'], name='events_even_workspa_741f99_idx'), models.Index(fields=['workspace', 'source', 'kind'], name='events_even_workspa_6d3314_idx'), models.Index(fields=['workspace', 'level', '-last_seen_at'], name='events_even_workspa_e6c604_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('key', ''), _negated=True), fields=('workspace', 'source', 'key'), name='uniq_event_workspace_source_key')],
            },
        ),
    ]
