# Generated by Django 6.1.1 on 2026-10-02 18:38

from django.conf import settings
import re

from django.db import migrations, models

_PREFIX = re.compile(r"^\[([a-z0-9][a-z0-9-]{0,63})\] ")


def backfill(apps, schema_editor):
    """File existing rows: the `[workspace]` prefix a generated tool already
    wrote into the summary, else the caller's sole workspace, else none."""
    Log = apps.get_model("mcp", "MCPAuditLog")
    Membership = apps.get_model("workspaces", "WorkspaceMembership")
    sole: dict[int, str] = {}
    for uid in Log.objects.exclude(user_id=None).values_list("user_id", flat=True).distinct():
        slugs = list(Membership.objects.filter(user_id=uid).values_list("workspace_id", flat=True)[:2])
        if len(slugs) == 1:
            sole[uid] = slugs[0]
    for row in Log.objects.filter(workspace_slug="").only("pk", "user_id", "args_summary").iterator():
        m = _PREFIX.match(row.args_summary or "")
        slug = m.group(1) if m else sole.get(row.user_id, "")
        if slug:
            Log.objects.filter(pk=row.pk).update(workspace_slug=slug)



class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0011_admin_role"),
        ("mcp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mcpauditlog",
            name="workspace_slug",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddIndex(
            model_name="mcpauditlog",
            index=models.Index(
                fields=["workspace_slug", "-created_at"],
                name="mcp_audit_l_workspa_03980b_idx",
            ),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
