# Generated by Django 5.2.12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0035_agent_delegation'),
        ('projects', '0009_home_unscoped_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='default_identity_agent',
            field=models.ForeignKey(
                blank=True,
                help_text="Fallback GitHub identity for a project turn with no agent of "
                "its own (apps.agents.delegations.turn_agent) — lends this agent's "
                "owner's delegated token and git identity. Unset keeps the turn's "
                "existing refusal: no shared fallback.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='default_identity_projects',
                to='agents.agent',
            ),
        ),
    ]
