# Generated by Django 6.1.1 on 2026-10-04 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0009_home_unscoped_projects"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="projectcontext",
            name="scope",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=40
            ),
        ),
        migrations.AlterField(
            model_name="projectcontext",
            name="context_type",
            field=models.CharField(
                choices=[
                    ("current_work", "Current Work"),
                    ("next_step", "Next Step"),
                    ("summary", "Summary"),
                    ("note", "Note"),
                    ("insight", "Insight"),
                    ("learning", "Learning"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ProjectRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        help_text='Workflow kind, e.g. "ddd".', max_length=40
                    ),
                ),
                ("run_id", models.CharField(max_length=255, unique=True)),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="What the run is about within the kind (DDD: the narrative slug).",
                        max_length=200,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=300)),
                (
                    "status",
                    models.CharField(
                        db_index=True,
                        default="running",
                        help_text='"running" while live; else the kind\'s terminal status.',
                        max_length=40,
                    ),
                ),
                ("phase", models.CharField(blank=True, default="", max_length=40)),
                ("iteration", models.IntegerField(default=0)),
                (
                    "summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Small kind-defined digest for lists.",
                    ),
                ),
                (
                    "state",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="The kind's full run state document.",
                    ),
                ),
                ("state_version", models.PositiveIntegerField(default=0)),
                (
                    "holder",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The runner/host that last wrote the state.",
                        max_length=200,
                    ),
                ),
                ("holder_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_runs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "kind", "-updated_at"],
                        name="projects_pr_project_3958ec_idx",
                    ),
                    models.Index(
                        fields=["project", "kind", "subject"],
                        name="projects_pr_project_fad729_idx",
                    ),
                ],
            },
        ),
    ]
