// GENERATED by assets/brand/generate.py from assets/brand/mark.py — do not edit.
// The canopy mark (the low dome), drawn in currentColor so it takes the text colour
// of wherever it sits. Size it with a height class; the width follows its aspect.
import type { SVGProps } from 'react'

export function CanopyMark(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="-8.09 33.00 116.18 46.50" role="img" aria-label="Canopy" {...props}>
      <path d="M-1.962 70.000A60 60 0 0 1 26.556 44.770" fill="none" stroke="currentColor" stroke-width="13" stroke-linecap="butt" /><path d="M32.458 42.622A60 60 0 0 1 67.542 42.622" fill="none" stroke="currentColor" stroke-width="13" stroke-linecap="butt" /><path d="M73.444 44.770A60 60 0 0 1 101.962 70.000" fill="none" stroke="currentColor" stroke-width="13" stroke-linecap="butt" /><circle cx="33" cy="72" r="7" fill="currentColor" /><circle cx="50" cy="72" r="7" fill="currentColor" /><circle cx="67" cy="72" r="7" fill="currentColor" />
    </svg>
  )
}
