import { useCallback, useEffect, useRef, useState } from 'react'

import {
  getRunnerMint,
  startRunnerMint,
  submitRunnerMintCode,
  type RunnerMint,
} from '@/api/harness'

// Sign a cloud runner back in to Claude, from a browser.
//
// A subscription token expires often, and when one does the box does not slow
// down — it stops, and stays stopped until a person signs in again. Until now
// that person needed a terminal on the box, which is why a signed-out runner
// could sit dead for a day.
//
// canopy-web cannot mint the token itself: `claude setup-token` runs PKCE with a
// verifier generated by whoever starts it, so the exchange has to happen where
// the CLI is. The runner does it; this screen is the relay, and shows a human
// exactly two things — a link to open, and a box to paste the code back into.
//
// The minted token never reaches this component. The runner sends it straight to
// canopy-web, so the only secret that ever touches a browser is the single-use
// authorization code.

/** How long to keep polling for the runner to pick the request up.
 *  A cloud runner polls on its own tick (~15s), so a URL usually lands within
 *  one; this is generous enough for a slow tick and short enough that a runner
 *  which is simply DOWN says so rather than spinning forever. */
const WAIT_LIMIT_MS = 90_000
const POLL_MS = 3_000

export function RunnerReauth({ runnerId, onSignedIn }: {
  runnerId: string
  /** Lets the parent refresh its masked credential status once a token lands. */
  onSignedIn?: () => void
}) {
  const [mint, setMint] = useState<RunnerMint | null>(null)
  const [code, setCode] = useState('')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [waitedOut, setWaitedOut] = useState(false)
  const startedWaiting = useRef<number | null>(null)

  const refresh = useCallback(async () => {
    try {
      setMint(await getRunnerMint(runnerId))
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Could not read the sign-in state')
    }
  }, [runnerId])

  useEffect(() => { void refresh() }, [refresh])

  // Poll only while the RUNNER owes something. Once the URL is up the ball is
  // with the human and nothing will change until they act, so polling then would
  // be a timer that can never fire usefully.
  const waitingOnRunner = mint?.status === 'requested' || mint?.status === 'completing'
  useEffect(() => {
    if (!waitingOnRunner) {
      startedWaiting.current = null
      setWaitedOut(false)
      return
    }
    startedWaiting.current ??= Date.now()
    const t = window.setInterval(() => {
      if (Date.now() - (startedWaiting.current ?? 0) > WAIT_LIMIT_MS) {
        setWaitedOut(true)
        return
      }
      void refresh()
      if (mint?.status === 'completing') onSignedIn?.()
    }, POLL_MS)
    return () => window.clearInterval(t)
  }, [waitingOnRunner, refresh, mint?.status, onSignedIn])

  const run = async (fn: () => Promise<RunnerMint>) => {
    setBusy(true)
    setError(null)
    try {
      setMint(await fn())
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Something went wrong')
    } finally {
      setBusy(false)
    }
  }

  const start = () => run(async () => {
    setCode('')
    setWaitedOut(false)
    startedWaiting.current = null
    return startRunnerMint(runnerId)
  })

  const submit = () => run(async () => {
    const m = await submitRunnerMintCode(runnerId, code)
    setCode('')
    onSignedIn?.()
    return m
  })

  // Narrowed through `mint` itself rather than a hoisted `mint?.status`: the
  // optional chain reads fine but does not narrow, so every `mint.` below then
  // needs a non-null assertion. `tsc -b` catches that; `tsc --noEmit` does not.
  const status = mint?.status
  const idle = !mint || status === 'done' || status === 'failed'

  return (
    <section className="rounded-md border border-border p-3" data-testid="runner-reauth">
      <div className="flex items-baseline justify-between gap-3">
        <h4 className="text-sm font-semibold">Sign in to Claude</h4>
        {/* ALWAYS offered, not only when idle. A link is good for minutes, so a
            sign-in left half-done is the ordinary case — and with the button
            hidden mid-flight, a stale link was a dead end with nothing to click.
            That is exactly how a 68-minute-old link got used on 2026-09-08. */}
        <button
          type="button"
          onClick={start}
          disabled={busy}
          data-testid="reauth-start"
          className="rounded-md border border-border px-2 py-1 text-xs hover:bg-muted disabled:opacity-50"
        >
          {idle ? (status ? 'Sign in again' : 'Start sign-in') : 'Start again'}
        </button>
      </div>

      <p className="mt-1 text-xs text-muted-foreground">
        Re-authenticates this runner&rsquo;s Claude subscription without a terminal.
        You&rsquo;ll open one link and paste one code back.
      </p>

      {error && <p className="mt-2 text-sm text-destructive">{error}</p>}

      {status === 'requested' && !waitedOut && (
        <p className="mt-2 text-sm text-muted-foreground" data-testid="reauth-waiting">
          Waiting for the runner to start the sign-in&hellip;
        </p>
      )}

      {/* A runner that never picks the request up is the common real failure —
          it is, after all, a box we already suspect is unhealthy. Say that,
          rather than spinning: the operator's next move is a different one. */}
      {waitingOnRunner && waitedOut && (
        <p className="mt-2 text-sm text-destructive" data-testid="reauth-stalled">
          {status === 'requested'
            ? 'The runner hasn\u2019t picked this up. It may be offline \u2014 check it is running, then start again.'
            : 'The runner is taking longer than expected to finish. If it does not resolve, start again.'}
        </p>
      )}

      {mint !== null && mint.status === 'awaiting_code' && (
        <div className="mt-2 flex flex-col gap-2" data-testid="reauth-awaiting-code">
          <a
            href={mint.authorize_url}
            target="_blank"
            rel="noopener noreferrer"
            data-testid="reauth-url"
            className="inline-block w-fit rounded-md bg-primary px-3 py-1.5 text-sm font-medium text-primary-foreground hover:opacity-90"
          >
            Open Claude sign-in →
          </a>
          <p className="text-xs text-muted-foreground">
            Sign in as the account whose subscription this runner uses, then copy the
            code it shows you and paste it here. <strong>Do it now</strong> &mdash; the
            link is only good for a few minutes.
          </p>
          <div className="flex gap-2">
            <input
              value={code}
              onChange={(e) => setCode(e.target.value)}
              placeholder="Paste the code from Claude"
              data-testid="reauth-code"
              className="flex-1 rounded-md border border-border bg-background px-2 py-1 text-sm"
            />
            <button
              type="button"
              onClick={submit}
              disabled={busy || !code.trim()}
              data-testid="reauth-submit"
              className="rounded-md border border-border px-3 py-1 text-sm hover:bg-muted disabled:opacity-50"
            >
              Finish
            </button>
          </div>
        </div>
      )}

      {status === 'completing' && (
        <p className="mt-2 text-sm text-muted-foreground" data-testid="reauth-completing">
          Finishing the sign-in on the runner&hellip;
        </p>
      )}

      {status === 'done' && (
        <p className="mt-2 text-sm text-emerald-600" data-testid="reauth-done">
          Signed in. The runner is using the new token.
        </p>
      )}

      {mint !== null && mint.status === 'failed' && (
        <p className="mt-2 text-sm text-destructive" data-testid="reauth-failed">
          {mint.detail || 'The sign-in did not complete.'}
        </p>
      )}
    </section>
  )
}
