"""Drive `claude setup-token` on the box so a human can re-auth from a browser.

WHY THIS EXISTS. A cloud runner authenticates with a `CLAUDE_CODE_OAUTH_TOKEN`
minted by `claude setup-token`. Those expire often, and when one does the box
does not slow down — it stops, and stays stopped until a person re-authenticates
it. Until now that person needed a terminal on the box.

WHY IT IS SHAPED LIKE THIS. `setup-token` runs a PKCE flow whose verifier is
generated by whoever starts it, so canopy-web cannot complete an exchange for a
code a browser collected — it is not the OAuth client and must not pretend to be
(the client id belongs to Claude Code). The runner sidesteps that by letting the
REAL CLI run its own flow under a pty: `claude` stays the OAuth client, and
canopy-web only ferries a URL out to a human and a code back. Nothing upstream
is impersonated and no verifier ever leaves the box.

WHAT MAKES IT TRACTABLE. `setup-token` is an Ink TUI — with no tty it prints
nothing and waits forever, so it cannot be driven with pipes. But it renders the
authorize URL on purpose ("Browser didn't open? Use the url below to sign in"),
which makes the URL a supported affordance rather than something scraped out of
a redraw. The parsing below is nonetheless written against a REAL capture
(`tests/fixtures/setup_token_pty.bin`), because a TUI's exact bytes — OSC-8
hyperlink wrappers, spinner frames, line-wrapping mid-URL — are not guessable.
"""
from __future__ import annotations

import os
import pty
import re
import select
import signal
import time

#: The CLI wraps the URL in an OSC-8 hyperlink, which puts the whole thing in
#: the terminal's *escape* stream — twice, and split by the wrap. Strip these
#: before anything else or the URL is recovered with control bytes embedded.
_OSC = re.compile(rb"\x1b\][^\x07\x1b]*(?:\x07|\x1b\\)")
_CSI = re.compile(rb"\x1b\[[0-9;?]*[ -/]*[@-~]")

#: `claude.com/cai/oauth/authorize`, NOT `claude.ai/oauth/...`. Worth stating:
#: the binary contains `https://claude.ai/oauth/...` strings too, and matching
#: those finds nothing at runtime.
_AUTHORIZE = re.compile(r"https://claude\.com/cai/oauth/authorize\?[^\s\x00-\x1f\"'<>]+")

#: A setup-token is an OAuth token — `sk-ant-oat…`, distinct from an API key.
_TOKEN = re.compile(r"\bsk-ant-oat[A-Za-z0-9_\-]+")


def strip_terminal(raw: bytes) -> str:
    """Terminal bytes -> the text a human would see, plus the escaped URL.

    Deliberately keeps OSC-8 *payloads* rather than dropping them: the URL lives
    inside the hyperlink escape, so a naive "remove all escapes" pass throws away
    the one thing worth reading. Carriage returns go because the TUI redraws with
    them, which otherwise splices unrelated frames into one line.
    """
    text = _CSI.sub(b"", raw)
    # OSC-8 opens as ESC ] 8 ; id=… ; <URL> BEL — keep everything after the last
    # ';' in the introducer, which is the URL itself.
    def _keep_url(m: "re.Match[bytes]") -> bytes:
        body = m.group(0)
        url = body.rsplit(b";", 1)[-1].rstrip(b"\x07\x1b\\")
        # Newline-delimited, and that is load-bearing rather than tidiness. The
        # hyperlink escape sits flush against the visible copy the TUI also
        # prints, so without a separator the two run together and the URL regex
        # — which cannot stop at "https" — happily matches one-and-a-bit copies.
        # The result starts correctly, ends in garbage, and fails only in a
        # browser. Caught by the real capture; a hand-written fixture would not
        # have had the adjacency that causes it.
        return b"\n" + url + b"\n"
    text = _OSC.sub(_keep_url, text)
    return text.decode("utf-8", "replace").replace("\r", "\n")


def extract_authorize_url(raw: bytes) -> str | None:
    """The URL to put in front of a human, or None if it has not rendered yet."""
    # The TUI prints the URL twice — once inside the hyperlink escape and once as
    # visible text that it WRAPS at the terminal width. Longest wins: the wrapped
    # copy is truncated, and a truncated authorize URL fails on an invalid-request
    # page rather than anything that looks like our bug.
    found = _AUTHORIZE.findall(strip_terminal(raw))
    return max(found, key=len) if found else None


def extract_token(raw: bytes) -> str | None:
    """The minted long-lived token, once the exchange has completed."""
    m = _TOKEN.search(strip_terminal(raw))
    return m.group(0) if m else None


class MintTimeout(RuntimeError):
    """The CLI never reached the expected step. Always fatal to the attempt:
    a half-driven TUI is not a state worth resuming."""


class MintSession:
    """One `claude setup-token` run, held open across two HTTP round-trips.

    The session is deliberately short-lived and single-use. A mint that is
    started and never finished holds a pty and a child process, so `close()` is
    unconditional and every wait is bounded — an operator who wanders off must
    not strand a process on the box.
    """

    def __init__(self, argv: tuple[str, ...] = ("claude", "setup-token"),
                 env: dict[str, str] | None = None) -> None:
        self._argv = argv
        self._env = env
        self._pid: int | None = None
        self._fd: int | None = None
        self._buf = b""

    # ── lifecycle ──────────────────────────────────────────────────────────
    def start(self, timeout: float = 60.0) -> str:
        """Spawn the CLI and return the URL a human must open."""
        env = dict(os.environ if self._env is None else self._env)
        # The box has no display. Left alone, `claude` tries to open a browser
        # and (on a headless host) can block or emit noise; the URL we want is
        # printed either way, so the launch is simply neutralised.
        env["BROWSER"] = "/usr/bin/true"
        pid, fd = pty.fork()
        if pid == 0:  # pragma: no cover — the child never returns
            os.execvpe(self._argv[0], list(self._argv), env)
            os._exit(1)
        self._pid, self._fd = pid, fd
        url = self._pump(timeout, extract_authorize_url)
        if url is None:
            self.close()
            raise MintTimeout("setup-token never printed an authorize URL")
        return url

    def submit_code(self, code: str, timeout: float = 90.0) -> str:
        """Type the code the human pasted, and return the minted token."""
        if self._fd is None:
            raise MintTimeout("this mint session is not running")
        os.write(self._fd, code.strip().encode() + b"\r")
        token = self._pump(timeout, extract_token)
        self.close()
        if token is None:
            raise MintTimeout("setup-token never printed a token — the code may "
                              "have been wrong, expired, or already used")
        return token

    def close(self) -> None:
        """Idempotent: called on every exit path, including the happy one."""
        if self._pid is not None:
            try:
                os.kill(self._pid, signal.SIGKILL)
                os.waitpid(self._pid, 0)
            except (ProcessLookupError, ChildProcessError, OSError):
                pass
            self._pid = None
        if self._fd is not None:
            try:
                os.close(self._fd)
            except OSError:
                pass
            self._fd = None

    # ── internals ──────────────────────────────────────────────────────────
    def _pump(self, timeout, extract):
        """Read until `extract` finds something, or time runs out.

        Reads accumulate into one buffer rather than being examined per-chunk:
        the URL routinely arrives split across reads, and a per-chunk match would
        find it only when the boundaries happened to fall kindly.
        """
        deadline = time.time() + timeout
        while time.time() < deadline:
            ready, _, _ = select.select([self._fd], [], [], 0.5)
            if not ready:
                continue
            try:
                chunk = os.read(self._fd, 65536)
            except OSError:  # the child exited and closed the pty
                break
            if not chunk:
                break
            self._buf += chunk
            found = extract(self._buf)
            if found:
                return found
        return extract(self._buf)
