"""What is NOT a chat message, defined once.

A Claude Code transcript encodes far more than the conversation: the harness
injects task notifications, system reminders and local command output as records
of `type: "user"`, indistinguishable by shape from something a person typed. Ship
those verbatim and the machine's own event stream renders on the HUMAN's side of
the chat — observed on labs 2026-07-26, where a session's transcript read:

    [1146] role=user  <task-notification> … Monitor event: "Labs deploy run …"
    [1160] role=user  <task-notification> … Deploy to Fargate: success
    [1168] role=user  Can you add the ability for me to attach something…

Only the last of those was the user.

This lives SERVER-side on purpose. The runner has its own copy of this rule for
the cheap preview tail (`canopy_runner.transcript._is_system_noise`), but a
producer-side filter only ever covers producers that have been updated — and the
runner is a laptop daemon on a checkout that lags. `persist_transcript_rows` is
the single durable write path for every producer, so enforcing it there is what
actually makes the guarantee hold.
"""
from __future__ import annotations

# Matched case-insensitively against the message's leading text.
SYSTEM_NOISE_PREFIXES = (
    "<task-notification>",
    "[system notification",
    "<system-reminder>",
    "caveat: the messages below were generated by the user while running",
    "<local-command-stdout>",
    # Invoking a Skill injects its whole body as a `type: "user"` record opening
    # with this line — so the skill's instructions rendered as if the human had
    # pasted them. Found 2026-07-26 in a rebuilt session: 1 noise row in 110,
    # the only prefix the original list missed.
    "base directory for this skill:",
    # Hitting escape in emdash writes this as a `type: "user"` record, so it
    # rendered as a message YOU sent — in your own bubble, on your own side of
    # the chat. You didn't type it; Claude Code did. Two variants observed
    # across the fleet (81 rows): the bare marker and "…for tool use", both
    # caught by this prefix. The information it carries — that the turn was
    # interrupted — is already obvious from the message that follows it.
    "[request interrupted by user",
)


def scrub_nul(value):
    """Strip NUL bytes from every string in `value` (str / dict / list).

    Postgres rejects 0x00 outright in text and jsonb. A tool result is raw bytes
    from whatever the tool touched, so a `Read` of a compressed or binary file
    carries one straight into the write path — observed on labs 2026-07-26: one
    row in 683 took down the whole batch with a 500, and because the write is a
    single transaction and the runner retries forever, that session's history
    could never rebuild.

    Server-side for the same reason the noise filter is (see the module
    docstring): the runner has its own copy, but a producer-side scrub only
    covers producers that have been updated, and the runner is a laptop daemon
    on a checkout that lags. This is the single durable write path, so enforcing
    it here is what makes the guarantee hold.
    """
    if isinstance(value, str):
        return value.replace("\x00", "") if "\x00" in value else value
    if isinstance(value, dict):
        return {k: scrub_nul(v) for k, v in value.items()}
    if isinstance(value, list):
        return [scrub_nul(v) for v in value]
    return value


def is_system_noise(text: str) -> bool:
    """True when this record is harness output wearing a user record's clothes.

    Prefix-anchored, never a substring search: a human quoting
    "<system-reminder>" while asking about one is a real message and must
    survive. Only a record that BEGINS with the marker is the harness talking.
    """
    if not text:
        return False
    head = text.lstrip().lower()
    return any(head.startswith(p) for p in SYSTEM_NOISE_PREFIXES)
