# Generated by Django 5.2.12 on 2026-09-14 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0008_rename_auto_join_domains_self_join_domains'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Lowercased. The identity as ASSERTED — see `auth_result` for whether the sending domain backed it up.', max_length=254)),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
                ('auth_result', models.CharField(choices=[('none', 'Unverified'), ('spf', 'SPF only (envelope sender)'), ('dkim', 'DKIM signed'), ('dmarc', 'DMARC aligned')], default='none', help_text="The BEST grade seen from this address so far. Best rather than latest: one forwarded message that breaks SPF should not downgrade a correspondent, and a rule asking 'has this domain ever proved itself' wants the high-water mark.", max_length=8)),
                ('last_auth_result', models.CharField(choices=[('none', 'Unverified'), ('spf', 'SPF only (envelope sender)'), ('dkim', 'DKIM signed'), ('dmarc', 'DMARC aligned')], default='none', help_text='The grade on the most recent message. Kept beside the best one because a DROP is the interesting signal — a correspondent who always passed DMARC and suddenly does not is worth noticing.', max_length=8)),
                ('auth_detail', models.TextField(blank=True, default='', help_text='The raw Authentication-Results header the grade came from, for audit. Kept because a disputed grade is unanswerable without it.')),
                ('notes', models.TextField(blank=True, default='', help_text='Free text a human or an agent has written about this person.')),
                ('attributes', models.JSONField(blank=True, default=dict, help_text="Structured facts, e.g. {'org': 'LLO Foo', 'connect_opp': 42}. A CACHE of what other systems say, never the authority: agent execution calls those systems and honours their ACLs in real time, so nothing here may be the thing that grants.")),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('message_count', models.PositiveIntegerField(default=0, help_text='Inbound messages attributed to this contact.')),
                ('user', models.ForeignKey(blank=True, help_text='Set once this person has authenticated for real and become a canopy user. NULL is the normal state: most contacts are people an agent corresponds with and nothing more. Linking here still grants nothing — membership is a separate, explicit act.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_records', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(help_text="The tenant whose knowledge this is. A person dealt with by two workspaces has two contacts, deliberately — merging them would leak one tenant's dealings into another.", on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['workspace', 'last_seen_at'], name='contacts_co_workspa_6e9574_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'email'), name='uniq_contact_per_workspace_email')],
            },
        ),
    ]
