# Generated by Django 5.2.12 on 2026-09-14 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('tokens', '0011_embedauditlog'),
        ('workspaces', '0008_rename_auto_join_domains_self_join_domains'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contact',
            name='uniq_contact_per_workspace_email',
        ),
        migrations.AddField(
            model_name='contact',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='tokens.appcredential'),
        ),
        migrations.AddField(
            model_name='contact',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='blocked_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='source',
            field=models.CharField(choices=[('email', "Wrote to an agent's inbox"), ('embed', 'Used an agent embedded in a connected site')], default='email', help_text='Which channel this person arrived through. Not cosmetic: it says which identity column is the real key, and therefore what a duplicate would even mean.', max_length=8),
        ),
        migrations.AlterField(
            model_name='contact',
            name='auth_result',
            field=models.CharField(choices=[('none', 'Unverified'), ('spf', 'SPF only (envelope sender)'), ('app_secret', 'App credential (proves the app, not the person)'), ('dkim', 'DKIM signed'), ('app_signed', 'Signed assertion from the app'), ('dmarc', 'DMARC aligned'), ('app_signed_origin', 'Signed assertion from a framed origin')], default='none', help_text="The BEST grade seen from this address so far. Best rather than latest: one forwarded message that breaks SPF should not downgrade a correspondent, and a rule asking 'has this domain ever proved itself' wants the high-water mark.", max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Lowercased. The identity as ASSERTED — see `auth_result` for how well it was backed up. BLANK is normal for a widget visitor: a host identifies its people by its own id and may never know an address, and demanding one would have forced a fake. On an embed contact this is a DESCRIPTION rather than a key: it is unique only where the email channel established it.', max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_auth_result',
            field=models.CharField(choices=[('none', 'Unverified'), ('spf', 'SPF only (envelope sender)'), ('app_secret', 'App credential (proves the app, not the person)'), ('dkim', 'DKIM signed'), ('app_signed', 'Signed assertion from the app'), ('dmarc', 'DMARC aligned'), ('app_signed_origin', 'Signed assertion from a framed origin')], default='none', help_text='The grade on the most recent message. Kept beside the best one because a DROP is the interesting signal — a correspondent who always passed DMARC and suddenly does not is worth noticing.', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message_count',
            field=models.PositiveIntegerField(default=0, help_text='Interactions attributed to this contact — inbound messages, and widget conversations started.'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['app', 'external_id'], name='contacts_co_app_id_541697_idx'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('email', ''), _negated=True), ('source', 'email')), fields=('workspace', 'email'), name='uniq_contact_per_workspace_email'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('workspace', 'app', 'external_id'), name='uniq_contact_per_app_external_id'),
        ),
    ]
