# Generated by Django 6.1.1 on 2026-09-19 03:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_contact_beyond_email"),
        ("tokens", "0014_githubconnection_access_token"),
        ("workspaces", "0008_rename_auto_join_domains_self_join_domains"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="auth_result",
            field=models.CharField(
                choices=[
                    ("none", "Unverified"),
                    ("spf", "SPF only (envelope sender)"),
                    ("app_secret", "App credential (proves the app, not the person)"),
                    ("dkim", "DKIM signed"),
                    ("app_signed", "Signed assertion from the app"),
                    ("slack", "Slack account (event signed by Slack)"),
                    ("dmarc", "DMARC aligned"),
                    ("app_signed_origin", "Signed assertion from a framed origin"),
                ],
                default="none",
                help_text="The BEST grade seen from this address so far. Best rather than latest: one forwarded message that breaks SPF should not downgrade a correspondent, and a rule asking 'has this domain ever proved itself' wants the high-water mark.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="last_auth_result",
            field=models.CharField(
                choices=[
                    ("none", "Unverified"),
                    ("spf", "SPF only (envelope sender)"),
                    ("app_secret", "App credential (proves the app, not the person)"),
                    ("dkim", "DKIM signed"),
                    ("app_signed", "Signed assertion from the app"),
                    ("slack", "Slack account (event signed by Slack)"),
                    ("dmarc", "DMARC aligned"),
                    ("app_signed_origin", "Signed assertion from a framed origin"),
                ],
                default="none",
                help_text="The grade on the most recent message. Kept beside the best one because a DROP is the interesting signal — a correspondent who always passed DMARC and suddenly does not is worth noticing.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="source",
            field=models.CharField(
                choices=[
                    ("email", "Wrote to an agent's inbox"),
                    ("embed", "Used an agent embedded in a connected site"),
                    ("slack", "Messaged an agent in the connected Slack"),
                ],
                default="email",
                help_text="Which channel this person arrived through. Not cosmetic: it says which identity column is the real key, and therefore what a duplicate would even mean.",
                max_length=8,
            ),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("source", "slack"), models.Q(("external_id", ""), _negated=True)
                ),
                fields=("workspace", "external_id"),
                name="uniq_contact_per_slack_user",
            ),
        ),
    ]
