# Generated by Django 6.1.1 on 2026-09-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0003_slack_contacts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="auth_result",
            field=models.CharField(
                choices=[
                    ("none", "Unverified"),
                    ("spf", "SPF only (envelope sender)"),
                    ("app_secret", "App credential (proves the app, not the person)"),
                    ("dkim", "DKIM signed"),
                    ("app_signed", "Signed assertion from the app"),
                    ("slack", "Slack account (event signed by Slack)"),
                    ("dmarc", "DMARC aligned"),
                    ("dkim_aligned", "DKIM signed by the From: domain"),
                    ("app_signed_origin", "Signed assertion from a framed origin"),
                ],
                default="none",
                help_text="The BEST grade seen from this address so far. Best rather than latest: one forwarded message that breaks SPF should not downgrade a correspondent, and a rule asking 'has this domain ever proved itself' wants the high-water mark.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="last_auth_result",
            field=models.CharField(
                choices=[
                    ("none", "Unverified"),
                    ("spf", "SPF only (envelope sender)"),
                    ("app_secret", "App credential (proves the app, not the person)"),
                    ("dkim", "DKIM signed"),
                    ("app_signed", "Signed assertion from the app"),
                    ("slack", "Slack account (event signed by Slack)"),
                    ("dmarc", "DMARC aligned"),
                    ("dkim_aligned", "DKIM signed by the From: domain"),
                    ("app_signed_origin", "Signed assertion from a framed origin"),
                ],
                default="none",
                help_text="The grade on the most recent message. Kept beside the best one because a DROP is the interesting signal — a correspondent who always passed DMARC and suddenly does not is worth noticing.",
                max_length=20,
            ),
        ),
    ]
