# Generated by Django 6.1.1 on 2026-09-24 00:01

import django.db.models.deletion
from django.db import migrations, models


def link_contacts_canopy_already_knew(apps, schema_editor):
    """Contacts recorded before this get their person too.

    The connection was knowable all along — `(app, external_id)` and `email`
    were already on every row — so leaving existing contacts unlinked would
    mean canopy knows two tenants share a person only for people it met after
    this deploy. Same keys as `services.person_for`, and deliberately not the
    Slack rows: a Slack id is not an identity across tenants, and inventing one
    here would be a guess baked into data.
    """
    Contact = apps.get_model("contacts", "Contact")
    Person = apps.get_model("contacts", "Person")

    for row in Contact.objects.exclude(app__isnull=True).exclude(external_id="").iterator():
        person, _ = Person.objects.get_or_create(
            app_id=row.app_id, external_id=row.external_id, defaults={"email": ""})
        Contact.objects.filter(pk=row.pk).update(person=person)

    for row in Contact.objects.filter(app__isnull=True).exclude(email="").iterator():
        if row.source == "slack":
            continue
        person, _ = Person.objects.get_or_create(
            app__isnull=True, email=row.email, defaults={"external_id": ""})
        Contact.objects.filter(pk=row.pk).update(person=person)


def unlink(apps, schema_editor):
    apps.get_model("contacts", "Contact").objects.update(person=None)
    apps.get_model("contacts", "Person").objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0005_alter_contact_auth_result_and_more"),
        ("tokens", "0019_site_serves_many_tenants"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "app",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_identities",
                        to="tokens.appcredential",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "people",
                "db_table": "contact_persons",
            },
        ),
        migrations.AddField(
            model_name="contact",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contacts",
                to="contacts.person",
            ),
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id__gt", "")),
                fields=("app", "external_id"),
                name="one_person_per_site_visitor",
            ),
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.UniqueConstraint(
                condition=models.Q(("app__isnull", True), ("email__gt", "")),
                fields=("email",),
                name="one_person_per_correspondent",
            ),
        ),
            migrations.RunPython(link_contacts_canopy_already_knew, unlink),
    ]
