# Generated by Django 6.1.1 on 2026-10-08 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0038_projects_and_tasks_final_shape"),
        ("contacts", "0008_slack_member_grade"),
        ("harness", "0067_failureinvestigation"),
        ("workspaces", "0013_system_accounts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="person",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="PersonAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "via",
                    models.CharField(
                        choices=[
                            ("envelope", "In an agent turn's caller envelope"),
                            ("api", "Through the REST/MCP API"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accesses",
                        to="contacts.person",
                    ),
                ),
                (
                    "reader_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="person_reads",
                        to="agents.agent",
                    ),
                ),
                (
                    "reader_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="person_reads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "turn",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="person_reads",
                        to="harness.turn",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person_accesses",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "contact_person_accesses",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["person", "created_at"],
                        name="contact_per_person__ea70e9_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PersonDigest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True, default="", max_length=2000)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_turn_ids", models.JSONField(blank=True, default=list)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="digests",
                        to="contacts.person",
                    ),
                ),
                (
                    "updated_by_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="person_digests",
                        to="agents.agent",
                    ),
                ),
                (
                    "updated_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="person_digests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person_digests",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "contact_person_digests",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("person", "workspace"),
                        name="one_digest_per_person_workspace",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PersonFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("role", "Role — who they are at work"),
                            ("project", "Project — work they are part of"),
                            (
                                "instance",
                                "Instance — a specific thing they work with (a bot, an app, a report)",
                            ),
                            (
                                "preference",
                                "Preference — how they like to work with agents",
                            ),
                            (
                                "correction",
                                "Correction — something an agent got wrong, to honour",
                            ),
                            (
                                "terminology",
                                "Terminology — the words they use for things",
                            ),
                        ],
                        max_length=16,
                    ),
                ),
                ("statement", models.CharField(max_length=500)),
                (
                    "basis",
                    models.CharField(
                        choices=[
                            (
                                "declared",
                                "Declared — the person said it, or a human asserted it",
                            ),
                            ("inferred", "Inferred — a model concluded it"),
                        ],
                        default="declared",
                        max_length=10,
                    ),
                ),
                (
                    "instance_ref",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                ("retracted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asserted_by_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="person_facts_asserted",
                        to="agents.agent",
                    ),
                ),
                (
                    "asserted_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="person_facts_asserted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facts",
                        to="contacts.person",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="person_facts",
                        to="agents.agentproject",
                    ),
                ),
                (
                    "retracted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="person_facts_retracted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_turn",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="person_facts",
                        to="harness.turn",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="superseded_by",
                        to="contacts.personfact",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person_facts",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "contact_person_facts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["person", "workspace", "created_at"],
                        name="contact_per_person__38ea78_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "kind__in",
                                [
                                    "role",
                                    "project",
                                    "instance",
                                    "preference",
                                    "correction",
                                    "terminology",
                                ],
                            )
                        ),
                        name="person_fact_kind_is_work_context",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("basis__in", ["declared", "inferred"])),
                        name="person_fact_basis_known",
                    ),
                ],
            },
        ),
    ]
