# Generated by Django 6.1.1 on 2026-10-08 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0009_person_brain"),
    ]

    operations = [
        migrations.AddField(
            model_name="personaccess",
            name="had_context",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="personfact",
            name="source_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mirrored_facts",
                to="contacts.contact",
            ),
        ),
    ]
