"""HCP v1 (apps/contacts/hcp.py), schema half: the grant, audit and idempotency
tables, and the entry fields on PersonFact. `entry_id` is added NULLABLE —
0013 gives every existing version chain its own id, and 0014 then makes it
required and adds the constraints that existing rows would violate today."""
# Generated by Django 6.1.1 on 2026-10-08 20:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0042_sender_trust"),
        ("contacts", "0011_mirror_contact_notes"),
        ("harness", "0070_callertoken_scoped"),
        ("workspaces", "0013_system_accounts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HcpIdempotencyKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=200)),
                ("method", models.CharField(max_length=8)),
                ("path", models.CharField(max_length=300)),
                ("body_hash", models.CharField(max_length=64)),
                ("status", models.PositiveSmallIntegerField()),
                ("response", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "contact_hcp_idempotency_keys",
            },
        ),
        migrations.CreateModel(
            name="PersonAuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("event_type", models.CharField(max_length=32)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("actor_id", models.CharField(max_length=200)),
                ("actor_type", models.CharField(max_length=8)),
                ("entry_id", models.UUIDField(blank=True, null=True)),
                ("related_entry_id", models.UUIDField(blank=True, null=True)),
                ("category", models.CharField(blank=True, default="", max_length=80)),
                ("purpose", models.CharField(blank=True, default="", max_length=500)),
                ("grant_id", models.UUIDField(blank=True, null=True)),
                ("detail", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "contact_person_audit_events",
                "ordering": ["-timestamp", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="PersonGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grant_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("channel", models.CharField(blank=True, default="", max_length=40)),
                ("host", models.CharField(blank=True, default="", max_length=200)),
                ("attributes", models.JSONField(blank=True, default=dict)),
                ("client_key", models.CharField(db_index=True, max_length=400)),
                ("client_name", models.CharField(max_length=200)),
                ("scopes", models.JSONField(default=list)),
                ("restrictions", models.JSONField(blank=True, default=list)),
                ("grant_type", models.CharField(default="persistent", max_length=12)),
                ("grantor", models.CharField(blank=True, default="", max_length=200)),
                (
                    "modality",
                    models.CharField(default="canopy-control-plane", max_length=40),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="active", max_length=10)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "contact_person_grants",
                "ordering": ["-issued_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="personfact",
            name="person_fact_basis_known",
        ),
        migrations.AddField(
            model_name="personfact",
            name="captured_by",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="personfact",
            name="category",
            field=models.CharField(default="work_context", max_length=80),
        ),
        migrations.AddField(
            model_name="personfact",
            name="confidence",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AddField(
            model_name="personfact",
            name="dimension",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="personfact",
            name="entry_id",
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="personfact",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="personfact",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="personfact",
            name="provenance_source",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="personfact",
            name="reason",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="personfact",
            name="relationship",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="personfact",
            name="status",
            field=models.CharField(default="active", max_length=12),
        ),
        migrations.AddField(
            model_name="personfact",
            name="user_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="personfact",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="personfact",
            name="basis",
            field=models.CharField(
                choices=[
                    ("declared", "Declared — the person said it"),
                    ("inferred", "Inferred — a model concluded it"),
                    (
                        "attested",
                        "Attested — someone other than the person asserted it",
                    ),
                ],
                default="declared",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="personfact",
            index=models.Index(
                fields=["person", "workspace", "category", "status"],
                name="contact_per_person__677301_idx",
            ),
        ),
        migrations.AddField(
            model_name="hcpidempotencykey",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hcp_idempotency_keys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="personauditevent",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_events",
                to="contacts.person",
            ),
        ),
        migrations.AddField(
            model_name="personauditevent",
            name="turn",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="person_audit_events",
                to="harness.turn",
            ),
        ),
        migrations.AddField(
            model_name="personauditevent",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="person_audit_events",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="persongrant",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="person_grants",
                to="agents.agent",
            ),
        ),
        migrations.AddField(
            model_name="persongrant",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grants",
                to="contacts.person",
            ),
        ),
        migrations.AddField(
            model_name="persongrant",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="person_grants",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddConstraint(
            model_name="hcpidempotencykey",
            constraint=models.UniqueConstraint(
                fields=("user", "key"), name="hcp_idempotency_key_per_user"
            ),
        ),
        migrations.AddIndex(
            model_name="personauditevent",
            index=models.Index(
                fields=["person", "timestamp"], name="contact_per_person__fd773b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="personauditevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("actor_type__in", ["user", "agent", "system"])),
                name="person_audit_actor_type_known",
            ),
        ),
        migrations.AddIndex(
            model_name="persongrant",
            index=models.Index(
                fields=["person", "client_key", "issued_at"],
                name="contact_per_person__1ecf61_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="persongrant",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "revoked", "expired"])),
                name="person_grant_status_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="persongrant",
            constraint=models.CheckConstraint(
                condition=models.Q(("grant_type__in", ["temporary", "persistent"])),
                name="person_grant_type_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="persongrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("grant_type", "temporary"), _negated=True),
                    ("expires_at__isnull", False),
                    _connector="OR",
                ),
                name="person_grant_temporary_expires",
            ),
        ),
    ]
