# Generated by Django 6.1.1 on 2026-10-08 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0041_link_fact_subjects_to_projects"),
        ("contacts", "0011_mirror_contact_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonDigestMark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("digested_at", models.DateTimeField()),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person_digest_marks",
                        to="agents.agent",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="digest_marks",
                        to="contacts.person",
                    ),
                ),
            ],
            options={
                "db_table": "contact_person_digest_marks",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("person", "agent"),
                        name="one_digest_mark_per_person_agent",
                    )
                ],
            },
        ),
    ]
