# Generated by Django 6.1.1 on 2026-10-09 14:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0014_hcp_v1_constraints"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="persondigest",
            name="one_digest_per_person_workspace",
        ),
        migrations.DeleteModel(
            name="PersonDigest",
        ),
    ]
