# Generated by Django 6.1.1 on 2026-10-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0015_remove_people_digest"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="hcp_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="person",
            name="hcp_enabled_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
