# Generated by Django 6.1.1 on 2026-10-09 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0019_agent_memory_defaults"),
        ("workspaces", "0013_system_accounts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personfact",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="person_facts",
                to="workspaces.workspace",
            ),
        ),
        migrations.AlterField(
            model_name="persongrant",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="person_grants",
                to="workspaces.workspace",
            ),
        ),
    ]
