# Generated by Django 6.1.1 on 2026-10-09 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0020_personal_entries"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HcpAuthorizationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_hash", models.CharField(max_length=64, unique=True)),
                ("redirect_uri", models.CharField(max_length=500)),
                ("code_challenge", models.CharField(max_length=128)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "contact_hcp_codes",
            },
        ),
        migrations.CreateModel(
            name="HcpClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("operator", models.CharField(max_length=120)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("redirect_uris", models.JSONField(default=list)),
                ("allowed_scopes", models.JSONField(default=list)),
                ("first_party", models.BooleanField(default=False)),
                (
                    "webhook_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("webhook_secret_encrypted", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("disabled_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "contact_hcp_clients",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HcpRevocationDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payload", models.JSONField()),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(db_index=True)),
                (
                    "last_status",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("abandoned_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "contact_hcp_revocation_deliveries",
            },
        ),
        migrations.CreateModel(
            name="HcpToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("kind", models.CharField(max_length=8)),
                ("scopes", models.JSONField(default=list)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "contact_hcp_tokens",
            },
        ),
        migrations.RemoveConstraint(
            model_name="hcpidempotencykey",
            name="hcp_idempotency_key_per_user",
        ),
        migrations.AlterField(
            model_name="hcpidempotencykey",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hcp_idempotency_keys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hcpauthorizationcode",
            name="grant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hcp_codes",
                to="contacts.persongrant",
            ),
        ),
        migrations.AddField(
            model_name="hcpclient",
            name="registered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hcp_clients_registered",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hcpauthorizationcode",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="codes",
                to="contacts.hcpclient",
            ),
        ),
        migrations.AddField(
            model_name="hcpidempotencykey",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="idempotency_keys",
                to="contacts.hcpclient",
            ),
        ),
        migrations.AddField(
            model_name="persongrant",
            name="hcp_client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grants",
                to="contacts.hcpclient",
            ),
        ),
        migrations.AddConstraint(
            model_name="hcpidempotencykey",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user", "key"),
                name="hcp_idempotency_key_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="hcpidempotencykey",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client__isnull", False)),
                fields=("client", "key"),
                name="hcp_idempotency_key_per_client",
            ),
        ),
        migrations.AddField(
            model_name="hcprevocationdelivery",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revocation_deliveries",
                to="contacts.hcpclient",
            ),
        ),
        migrations.AddField(
            model_name="hcprevocationdelivery",
            name="grant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revocation_deliveries",
                to="contacts.persongrant",
            ),
        ),
        migrations.AddField(
            model_name="hcptoken",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tokens",
                to="contacts.hcpclient",
            ),
        ),
        migrations.AddField(
            model_name="hcptoken",
            name="grant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hcp_tokens",
                to="contacts.persongrant",
            ),
        ),
        migrations.AddIndex(
            model_name="hcptoken",
            index=models.Index(
                fields=["grant", "kind"], name="contact_hcp_grant_i_ec6b34_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="hcptoken",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["access", "refresh"])),
                name="hcp_token_kind_known",
            ),
        ),
    ]
