"""Harness output must never render as something the human said.

Claude Code writes task notifications, system reminders and local command output
as records of `type: "user"`, so the bridge that turns a transcript into Message
rows cannot tell them apart by shape. Observed on labs 2026-07-26: a session's
own deploy-monitor notifications were showing on the user's side of the chat.
"""
from __future__ import annotations

import pytest
from django.contrib.auth.models import User

from apps.canopy_sessions import services
from apps.canopy_sessions.models import Message, Session
from apps.canopy_sessions.transcript_noise import is_system_noise
from apps.workspaces.models import Workspace

pytestmark = pytest.mark.django_db


# --- the rule itself --------------------------------------------------------


@pytest.mark.parametrize(
    "text",
    [
        '<task-notification>\n<task-id>bxubj4jg3</task-id>\n<summary>Monitor event</summary>',
        "[SYSTEM NOTIFICATION - NOT USER INPUT]\nThis is an automated background-task event",
        "<system-reminder>\nAs you answer the user's questions…",
        "Caveat: The messages below were generated by the user while running local commands.",
        "<local-command-stdout></local-command-stdout>",
        "   <task-notification> leading whitespace still counts",
        # A Skill invocation: the harness injects the skill body as a user record.
        "Base directory for this skill: /Users/jj/.claude/plugins/cache/superpowers/…",
    ],
)
def test_harness_records_are_recognised(text):
    assert is_system_noise(text) is True


@pytest.mark.parametrize(
    "text",
    [
        "Can you add the ability for me to attach something to chat as well.",
        "why does <system-reminder> show up in my chat?",  # a human ASKING about one
        "the deploy printed <local-command-stdout> — is that normal?",
        "what is the base directory for this skill?",  # a human ASKING, not the injection
        "",
        "   ",
    ],
)
def test_real_messages_survive(text):
    # Prefix-anchored, never a substring search: quoting a marker while asking
    # about it is a real message.
    assert is_system_noise(text) is False


# --- the durable write path -------------------------------------------------


def _session():
    user = User.objects.create_user("jj", "jj@dimagi.com", "pw")
    ws = Workspace.objects.create(slug="w1", display_name="W1", created_by=user)
    return Session.objects.create(workspace=ws, origin=Session.ORIGIN_RUNNER, title="s")


def test_persist_drops_harness_records_but_keeps_the_conversation():
    session = _session()

    written = services.persist_transcript_rows(
        session,
        [
            {"index": 0, "role": "user", "text": "ship the fix"},
            {"index": 1, "role": "assistant", "text": "on it"},
            {"index": 2, "role": "user", "text": "<task-notification>\n<task-id>abc</task-id>"},
            {"index": 3, "role": "user", "text": "<system-reminder>\nremember this"},
            {"index": 4, "role": "assistant", "text": "deployed"},
        ],
    )

    kept = list(
        Message.objects.filter(session=session).order_by("turn_index").values_list("plaintext", flat=True)
    )
    assert kept == ["ship the fix", "on it", "deployed"]
    assert written == 3


def test_dropping_noise_does_not_shift_the_ordinals_of_real_messages():
    """turn_index is the transcript ordinal — the identity the live stream,
    catch-up and backfill all key on. Renumbering around a dropped row would make
    the same record arrive under two different indices and duplicate it."""
    session = _session()

    services.persist_transcript_rows(
        session,
        [
            {"index": 7, "role": "user", "text": "<task-notification>\nnoise"},
            {"index": 8, "role": "assistant", "text": "real reply"},
        ],
    )

    assert Message.objects.get(session=session).turn_index == 8


def test_an_assistant_record_is_never_dropped_by_the_filter():
    """The rule targets harness records masquerading as USER input. Assistant
    text that happens to quote a marker is still the agent talking."""
    session = _session()

    services.persist_transcript_rows(
        session,
        [{"index": 0, "role": "assistant", "text": "<system-reminder> is injected by the harness"}],
    )

    assert Message.objects.filter(session=session).count() == 1


def test_re_shipping_a_dropped_record_stays_a_no_op():
    """A runner that has not been updated re-ships the same noise every catch-up;
    it must never accumulate."""
    session = _session()
    rows = [{"index": 2, "role": "user", "text": "<task-notification>\nnoise"}]

    services.persist_transcript_rows(session, rows)
    services.persist_transcript_rows(session, rows)

    assert Message.objects.filter(session=session).count() == 0


# --- the cleanup command ----------------------------------------------------


def test_purge_is_a_dry_run_by_default():
    """It deletes rows, so it asks to be told twice."""
    from io import StringIO

    from django.core.management import call_command

    session = _session()
    Message.objects.create(
        session=session, turn_index=0, role=Message.USER,
        plaintext="<task-notification>\nnoise", content={},
    )
    out = StringIO()
    call_command("purge_transcript_noise", stdout=out)

    assert Message.objects.filter(session=session).count() == 1
    assert "Dry run" in out.getvalue()


def test_purge_apply_removes_only_the_harness_rows():
    from io import StringIO

    from django.core.management import call_command

    session = _session()
    Message.objects.create(
        session=session, turn_index=0, role=Message.USER,
        plaintext="ship the fix", content={},
    )
    Message.objects.create(
        session=session, turn_index=1, role=Message.USER,
        plaintext="<task-notification>\nnoise", content={},
    )
    Message.objects.create(
        session=session, turn_index=2, role=Message.ASSISTANT,
        plaintext="<system-reminder> is injected by the harness", content={},
    )

    call_command("purge_transcript_noise", "--apply", stdout=StringIO())

    kept = set(
        Message.objects.filter(session=session).values_list("plaintext", flat=True)
    )
    assert kept == {
        "ship the fix",
        "<system-reminder> is injected by the harness",  # assistant text is never noise
    }


def test_the_interrupt_marker_is_not_something_you_typed():
    """Hitting escape in emdash writes `[Request interrupted by user]` as a
    `type: "user"` record, so it rendered in your own bubble as if you had typed
    it. Both observed variants are caught (81 rows across the fleet)."""
    assert is_system_noise("[Request interrupted by user]")
    assert is_system_noise("[Request interrupted by user for tool use]")


def test_a_human_quoting_the_interrupt_marker_still_survives():
    """Prefix-anchored, never a substring search — asking about the marker is a
    real message and must not be swallowed."""
    assert not is_system_noise('why does "[Request interrupted by user]" show up?')


# --- the binding-tail path --------------------------------------------------
#
# The tail is the one transcript the server never inspected: a local session
# renders `RunnerBinding.tail` until its backfill lands, and the runner filters
# that tail itself. So for as long as the rule was enforced only on the durable
# paths, a runner on a lagging checkout could put anything in a user bubble —
# and did (2026-07-30: a superpowers/brainstorming skill body, injected as a
# `type: "user"` record, rendered as the human's own message on an ada session).


def _binding_with_tail(session, tail):
    from django.utils import timezone

    from apps.canopy_sessions.models import RunnerBinding
    from apps.harness.models import Runner

    runner = Runner.objects.create(
        name="jj-mbp", workspace=session.workspace, location=Runner.LOCAL,
        paired_by=session.workspace.created_by, host="jj@mbp", status=Runner.ONLINE,
        last_heartbeat_at=timezone.now(),
    )
    return RunnerBinding.objects.create(
        session=session, runner=runner, session_key="ada-demo",
        thread_key="emdash:ada-demo", host=runner.host,
        last_interacted_at=timezone.now(), tail=tail,
    )


def test_the_tail_drops_a_skill_body_a_lagging_runner_shipped():
    session = _session()
    binding = _binding_with_tail(session, [
        {"role": "user", "text": "go look at the fleet"},
        {"role": "assistant", "text": "I'll start by invoking the skill."},
        {"role": "user", "text": "Base directory for this skill: /Users/jj/.claude/…"},
    ])

    rows = services.tail_as_messages(session, binding)

    assert [r.plaintext for r in rows] == [
        "go look at the fleet",
        "I'll start by invoking the skill.",
    ]


def test_dropping_a_tail_row_does_not_shift_its_neighbours():
    """The tail's negative turn_index comes from the row's ORIGINAL position, so
    a dropped row leaves its slot empty. Renumbering would reorder the tail
    against itself as the filter's verdict changed."""
    session = _session()
    binding = _binding_with_tail(session, [
        {"role": "user", "text": "<task-notification>\nnoise"},
        {"role": "assistant", "text": "real reply"},
    ])

    rows = services.tail_as_messages(session, binding)

    assert [(r.turn_index, r.plaintext) for r in rows] == [(-1, "real reply")]


def test_an_assistant_tail_row_is_never_dropped():
    """Same scoping as the durable path: the rule is about records masquerading
    as human input."""
    session = _session()
    binding = _binding_with_tail(session, [
        {"role": "assistant", "text": "<system-reminder> is injected by the harness"},
    ])

    assert len(services.tail_as_messages(session, binding)) == 1


# --- one definition, not two ------------------------------------------------


def test_the_runner_and_the_server_cannot_disagree_about_the_rule():
    """The bug underneath the bug: the runner carried a PRIVATE copy of this
    list, the server carried another, and the server's grew two prefixes the
    runner's never did. Both now import `canopy_transcript.noise` — this asserts
    they still resolve to the same object, so re-introducing a second definition
    fails here rather than on someone's phone."""
    from canopy_runner import transcript as runner_transcript
    from canopy_transcript import SYSTEM_NOISE_PREFIXES

    from apps.canopy_sessions import transcript_noise

    assert transcript_noise.SYSTEM_NOISE_PREFIXES is SYSTEM_NOISE_PREFIXES
    assert runner_transcript._SYSTEM_NOISE_PREFIXES is SYSTEM_NOISE_PREFIXES
    assert runner_transcript._is_system_noise is transcript_noise.is_system_noise
