"""What is NOT a chat message, defined once for the server AND both runners.

A Claude Code transcript encodes far more than the conversation: the harness
injects task notifications, system reminders, local command output and whole
skill bodies as records of `type: "user"`, indistinguishable by shape from
something a person typed. Ship those verbatim and the machine's own event stream
renders on the HUMAN's side of the chat.

This lives in `canopy_transcript` — the transcript core both the server and the
runners already depend on — because it was previously duplicated: the server's
copy in `apps.canopy_sessions.transcript_noise` and the runner's private
`_SYSTEM_NOISE_PREFIXES`. The two drifted (2026-07-26 -> 2026-07-30): two
prefixes were added server-side and the runner's copy never grew them, so a
skill body still rendered as the user's own message on the one path that trusts
the runner's filtering (the binding tail). A rule enforced in two places is a
rule that holds in one of them.
"""
from __future__ import annotations

# Matched case-insensitively against the message's leading text.
SYSTEM_NOISE_PREFIXES = (
    "<task-notification>",
    "[system notification",
    "<system-reminder>",
    "caveat: the messages below were generated by the user while running",
    "<local-command-stdout>",
    # Invoking a Skill injects its whole body as a `type: "user"` record opening
    # with this line — so the skill's instructions rendered as if the human had
    # pasted them. Found 2026-07-26 in a rebuilt session: 1 noise row in 110,
    # the only prefix the original list missed.
    "base directory for this skill:",
    # Hitting escape in emdash writes this as a `type: "user"` record, so it
    # rendered as a message YOU sent — in your own bubble, on your own side of
    # the chat. You didn't type it; Claude Code did. Two variants observed
    # across the fleet (81 rows): the bare marker and "…for tool use", both
    # caught by this prefix. The information it carries — that the turn was
    # interrupted — is already obvious from the message that follows it.
    "[request interrupted by user",
)


def is_system_noise(text: str) -> bool:
    """True when this record is harness output wearing a user record's clothes.

    Prefix-anchored, never a substring search: a human quoting
    "<system-reminder>" while asking about one is a real message and must
    survive. Only a record that BEGINS with the marker is the harness talking.
    """
    if not text:
        return False
    head = text.lstrip().lower()
    return any(head.startswith(p) for p in SYSTEM_NOISE_PREFIXES)
