# Generated by Django 5.2.12 on 2026-07-31 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0013_agent_workspace_not_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundMailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=254, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('last_push_at', models.DateTimeField(blank=True, null=True)),
                ('watch_expires_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_mailboxes', to='agents.agent')),
            ],
            options={
                'ordering': ['address'],
            },
        ),
    ]
