# Generated by Django 5.2.12 on 2026-07-31 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0001_initial'),
        ('workspaces', '0006_alter_workspace_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundPushConfig',
            fields=[
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='inbound_push_config', serialize=False, to='workspaces.workspace')),
                ('audience', models.CharField(blank=True, default='', max_length=500)),
                ('service_account', models.CharField(blank=True, default='', max_length=320)),
                ('watch_topic', models.CharField(blank=True, default='', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
