# Generated by Django 5.2.12 on 2026-08-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0002_inboundpushconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundmailbox',
            name='watch_error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
