# Generated by Django 5.2.12 on 2026-07-26 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_appcredential_delegatedtoken'),
        ('workspaces', '0002_workspaceinvite_uniq_ws_invite_live_per_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appcredential',
            name='provision_role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor')], default='editor', help_text="Role granted on first provisioning. Never 'owner'.", max_length=16),
        ),
        migrations.AddField(
            model_name='appcredential',
            name='provision_workspace',
            field=models.ForeignKey(blank=True, help_text='Tenant this credential may provision JIT/existing users into. Null = no provisioning power.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workspaces.workspace'),
        ),
        migrations.AddConstraint(
            model_name='appcredential',
            constraint=models.CheckConstraint(condition=models.Q(('provision_role', 'owner'), _negated=True), name='app_credential_provision_role_not_owner'),
        ),
    ]
