# Generated by Django 5.2.12 on 2026-07-26 09:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0003_appcredential_provision_role_and_more'),
        ('workspaces', '0003_workspacemembership_provisioned_by_app'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appcredential',
            name='app_credential_provision_role_not_owner',
        ),
        migrations.AddConstraint(
            model_name='appcredential',
            constraint=models.CheckConstraint(condition=models.Q(('provision_role__in', ['viewer', 'editor'])), name='app_credential_provision_role_valid'),
        ),
    ]
