# Generated by Django 5.2.12 on 2026-07-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add PersonalToken.expires_at.

    DELIBERATELY column-only — there is NO data step, and adding one later would
    be a mistake. Every pre-existing token keeps expires_at=NULL and therefore
    never expires. Backfilling `created_at + N days` would invalidate, at the
    instant of deploy, every token already older than N — including the cloud
    runner's PAT (held only in AWS Secrets Manager) and each agent user's token,
    none of which are enumerable from the owner-scoped /api/tokens/ endpoint.
    That would take the whole fleet offline simultaneously, and the recovery path
    (re-mint -> 1Password -> op inject -> redeploy) is manual. Old tokens are
    retired deliberately as each consumer is re-provisioned.
    """

    dependencies = [
        ('tokens', '0004_appcredential_provision_role_allowlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When this token stops authenticating. NULL means it never expires — which covers both tokens minted before expiry existed (grandfathered by migration 0005, which deliberately has no data step) and tokens minted with ttl_days=0. Enforced in lookup(), not by callers.', null=True),
        ),
    ]
