# Generated by Django 5.2.12 on 2026-09-13 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0021_bootstrap_report_turn_client'),
        ('tokens', '0005_personaltoken_expires_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCredentialAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_apps', to='agents.agent')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_agents', to='tokens.appcredential')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_credential_agents',
                'ordering': ['app_id', 'agent_id'],
                'constraints': [models.UniqueConstraint(fields=('app', 'agent'), name='one_row_per_app_agent')],
            },
        ),
    ]
