# Generated by Django 5.2.12 on 2026-09-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0006_appcredentialagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcredential',
            name='allowed_frame_origins',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
