# Generated by Django 5.2.12 on 2026-09-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0008_githubconnection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcredential',
            name='allowed_delegation_domains',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
