# Generated by Django 5.2.12 on 2026-09-14 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0009_alter_appcredential_allowed_delegation_domains'),
        ('workspaces', '0008_rename_auto_join_domains_self_join_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcredential',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='Workspace whose owners administer this app. Blank for rows registered before the Connected apps page existed.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embedded_apps', to='workspaces.workspace'),
        ),
    ]
