# Generated by Django 5.2.12 on 2026-09-14 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0010_appcredential_workspace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbedAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('exchange', 'Token exchange'), ('mint', 'Session mint'), ('connect', 'Site connected'), ('update', 'Site updated'), ('rotate', 'Secret rotated'), ('disconnect', 'Site disconnected')], db_index=True, max_length=20)),
                ('ok', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, default='', max_length=64)),
                ('app_name', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('subject_email', models.CharField(blank=True, db_index=True, default='', max_length=254)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('detail', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embed_audit_actor_rows', to=settings.AUTH_USER_MODEL)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_rows', to='tokens.appcredential')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embed_audit_subject_rows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'embed_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['app_name', '-created_at'], name='embed_audit_app_nam_bb5aad_idx'), models.Index(fields=['subject_email', '-created_at'], name='embed_audit_subject_03c2df_idx'), models.Index(fields=['event', '-created_at'], name='embed_audit_event_5d92b1_idx')],
            },
        ),
    ]
