# Generated by Django 5.2.12 on 2026-09-14 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_beyond_email'),
        ('tokens', '0011_embedauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcredential',
            name='public_keys',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='ContactToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_tokens', to='tokens.appcredential')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='contacts.contact')),
            ],
            options={
                'db_table': 'contact_tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
