# Generated by Django 5.2.12 on 2026-09-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0012_appcredential_public_keys_contacttoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcredential',
            name='show_on_canopy_pages',
            field=models.BooleanField(default=False),
        ),
    ]
