# Generated by Django 6.1.1 on 2026-09-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0013_appcredential_show_on_canopy_pages"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubconnection",
            name="access_token_enc",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="githubconnection",
            name="access_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
