# Generated by Django 6.1.1 on 2026-09-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0014_githubconnection_access_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="appcredential",
            name="resolvable_domains",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
