# Generated by Django 6.1.1 on 2026-09-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0015_resolvable_domains"),
    ]

    operations = [
        migrations.AddField(
            model_name="delegatedtoken",
            name="assurance",
            field=models.CharField(default="delegated", max_length=16),
        ),
    ]
