# Generated by Django 6.1.1 on 2026-09-22 22:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0016_delegated_assurance"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="appcredential",
            name="app_credential_provision_role_valid",
        ),
        migrations.RemoveField(
            model_name="appcredential",
            name="allowed_delegation_domains",
        ),
        migrations.RemoveField(
            model_name="appcredential",
            name="provision_role",
        ),
        migrations.RemoveField(
            model_name="appcredential",
            name="provision_workspace",
        ),
    ]
