# Generated by Django 6.1.1 on 2026-09-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0017_retire_token_exchange"),
    ]

    operations = [
        migrations.AddField(
            model_name="appcredential",
            name="jwks_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="HTTPS URL serving this site's JWKS. Preferred over pasting a key: canopy follows a rotation on its own.",
                max_length=500,
            ),
        ),
    ]
