# Generated by Django 6.1.1 on 2026-09-23 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def grant_each_site_to_its_home_tenant(apps, schema_editor):
    """Every site that already works keeps working, unchanged.

    A site registered before this had exactly one tenant — the workspace on its
    own row — and whatever `resolvable_domains` that tenant's owner had set.
    That is precisely one grant, so write it: without this, every live
    integration would mint its first token after deploy and be told the tenant
    had not authorized it.
    """
    AppCredential = apps.get_model("tokens", "AppCredential")
    AppCredentialTenant = apps.get_model("tokens", "AppCredentialTenant")
    rows = []
    for app in AppCredential.objects.exclude(workspace__isnull=True).iterator():
        rows.append(AppCredentialTenant(
            app_id=app.pk,
            workspace_id=app.workspace_id,
            # Carried across verbatim. These were set deliberately by an owner,
            # and re-deriving or re-validating them here would silently drop a
            # grant somebody made on purpose.
            resolvable_domains=list(app.resolvable_domains or []),
            created_by_id=app.created_by_id,
        ))
    AppCredentialTenant.objects.bulk_create(rows, ignore_conflicts=True)


def ungrant(apps, schema_editor):
    """Reverse: the grants carried nothing the site row did not already have."""
    apps.get_model("tokens", "AppCredentialTenant").objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0018_app_credential_jwks_url"),
        ("workspaces", "0008_rename_auto_join_domains_self_join_domains"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppCredentialTenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resolvable_domains", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_grants",
                        to="tokens.appcredential",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="granted_sites",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "app_credential_tenants",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("app", "workspace"),
                        name="one_grant_per_site_per_tenant",
                    )
                ],
            },
        ),
        migrations.RunPython(grant_each_site_to_its_home_tenant, ungrant),
        # The site-level column is gone: a grant somebody makes on their own
        # authority belongs on the grant, not on an identity shared by every
        # tenant the site serves.
        migrations.RemoveField(model_name="appcredential", name="resolvable_domains"),
    ]
