# Generated by Django 6.1.1 on 2026-09-24 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0019_site_serves_many_tenants"),
        ("workspaces", "0008_rename_auto_join_domains_self_join_domains"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appcredential",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                help_text="Workspace whose owners maintain this site's origins and keys. Transfers if they withdraw; blank for rows predating the Connected sites page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="embedded_apps",
                to="workspaces.workspace",
            ),
        ),
    ]
