# Generated by Django 6.1.1 on 2026-09-24 20:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0021_site_belongs_to_one_tenant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appcredential",
            name="token_hash",
        ),
    ]
