# Generated by Django 6.1.1 on 2026-09-29 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0024_host_grants"),
    ]

    operations = [
        migrations.AddField(
            model_name="appcredential",
            name="last_probe_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appcredential",
            name="last_probe_ok",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appcredential",
            name="last_probe_reason",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="appcredential",
            name="last_probe_step",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
