# Generated by Django 6.1.1 on 2026-09-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0027_mcp_oauth_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="appcredential",
            name="last_runner_requirements",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="contacttoken",
            name="runner_requirements",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="delegatedtoken",
            name="runner_requirements",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
