# Generated by Django 6.1.1 on 2026-09-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0028_runner_requirements"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostgrant",
            name="runner_requirements",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
