# Generated by Django 6.1.1 on 2026-10-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0029_host_grant_runner_requirements"),
    ]

    operations = [
        migrations.AddField(
            model_name="appcredential",
            name="mcp_apps_index",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
