# Generated by Django 6.1.1 on 2026-10-09 20:10

import django.db.models.deletion
from django.db import migrations, models


#: The live registration of connect-labs (labs.connect.dimagi.com) is trusted for
#: email identity (Jonathan, 2026-10-09). Matched on its name AND where it publishes
#: its keys, so a tenant that merely NAMED a site "connect-labs" is not trusted.
LABS_JWKS_PREFIX = "https://labs.connect.dimagi.com/"


def trust_labs(apps, schema_editor):
    AppCredential = apps.get_model("tokens", "AppCredential")
    n = (AppCredential.objects
         .filter(name="connect-labs", revoked_at__isnull=True, jwks_url__startswith=LABS_JWKS_PREFIX)
         .update(asserts_verified_email=True))
    print(f"\n  trusted connect-labs for email identity: {n} registration(s)")


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0022_retire_presumed_grants"),
        ("tokens", "0030_app_credential_mcp_apps_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="appcredential",
            name="asserts_verified_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contacttoken",
            name="verified_email",
            field=models.CharField(blank=True, default="", max_length=254),
        ),
        migrations.CreateModel(
            name="HcpFrameProof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proof_hash", models.CharField(max_length=64, unique=True)),
                ("cookie_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contacts.contact",
                    ),
                ),
            ],
            options={
                "db_table": "hcp_frame_proofs",
            },
        ),
        migrations.RunPython(trust_labs, migrations.RunPython.noop),
    ]
