# Generated by Django 5.2.12 on 2026-07-26 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_kind', models.CharField(max_length=32)),
                ('target_ref', models.CharField(max_length=200)),
                ('target_version', models.IntegerField(blank=True, null=True)),
                ('anchor_id', models.CharField(blank=True, default='', max_length=200)),
                ('kind', models.CharField(choices=[('comment', 'Comment'), ('suggestion', 'Suggestion')], default='comment', max_length=16)),
                ('body', models.TextField(blank=True, default='')),
                ('suggested_text', models.TextField(blank=True, default='')),
                ('author_name', models.CharField(blank=True, default='', max_length=200)),
                ('author_email', models.CharField(blank=True, default='', max_length=320)),
                ('channel', models.CharField(choices=[('web', 'Web'), ('email', 'Email'), ('gdoc', 'Google Doc'), ('manual', 'Manual'), ('api', 'API')], default='web', max_length=16)),
                ('source_ref', models.CharField(blank=True, default='', max_length=500)),
                ('state', models.CharField(choices=[('new', 'New'), ('triaged', 'Triaged'), ('answered', 'Answered'), ('declined', 'Declined')], default='new', max_length=16)),
                ('disposition_note', models.TextField(blank=True, default='')),
                ('resolved_in_version', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_kind', 'target_ref', 'state'], name='feedback_fe_target__5bbb4a_idx'), models.Index(fields=['channel', 'source_ref'], name='feedback_fe_channel_c59423_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_ref', ''), _negated=True), fields=('channel', 'source_ref'), name='uniq_feedback_channel_source_ref')],
            },
        ),
    ]
