# Generated by Django 6.1.1 on 2026-10-02 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0001_initial"),
        ("workspaces", "0010_workspace_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="workspaces.workspace",
            ),
        ),
    ]
