# Generated by Django 6.1.1 on 2026-10-09 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0002_feedback_workspace"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtifactView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_kind", models.CharField(max_length=32)),
                ("target_ref", models.CharField(max_length=200)),
                ("view_count", models.PositiveIntegerField(default=1)),
                ("first_viewed_at", models.DateTimeField(auto_now_add=True)),
                ("last_viewed_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifact_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["target_kind", "target_ref"],
                        name="feedback_ar_target__c7b282_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("target_kind", "target_ref", "user"),
                        name="uniq_artifact_view_user",
                    )
                ],
            },
        ),
    ]
