import { readFileSync } from 'node:fs'

import { beforeEach, describe, expect, it, vi } from 'vitest'

import fixture from './agui.fixture.json'
import { fromAgui, resetAguiState } from './agui'
import { sessionReducer } from './sessionReducer'
import type { SessionState, WsEvent } from './protocol'

/** The hook's own source. Read from disk rather than imported, because what is
 *  being checked is that the WIRING exists — which no behavioural test of a
 *  pure module can see. */
function hookSource(): string {
  return readFileSync(new URL('./useSessionSocket.ts', import.meta.url), 'utf8')
}

/**
 * The inverse projection, checked against the forward one.
 *
 * `agui.fixture.json` is GENERATED by `apps/canopy_sessions/agui.py` and a
 * Python test asserts it is current. So the round trip is proved across two
 * languages with a shared artifact — which is the only thing that can catch the
 * projection and its inverse drifting apart, since neither codebase can see the
 * other.
 */

beforeEach(() => resetAguiState())

type FixtureEntry = { canopy: WsEvent; agui: Array<Record<string, unknown>> }
const entries = fixture as unknown as FixtureEntry[]

/** Replay a fixture entry's AG-UI events through the inverse. */
function roundTrip(entry: FixtureEntry): WsEvent[] {
  return entry.agui.flatMap((event) => fromAgui(event))
}

describe('the round trip, against the server’s own output', () => {
  it('covers a real conversation, not just the easy frames', () => {
    // A fixture of two trivial events would pass forever while proving nothing
    // about a streamed reply or a tool call.
    const covered = new Set(entries.map((e) => e.canopy.event))
    expect(covered).toContain('chat.stream_start')
    expect(covered).toContain('chat.tool_use')
    expect(covered).toContain('chat.tool_result')
    expect(entries.length).toBeGreaterThanOrEqual(10)
  })

  it.each(entries.map((e) => [e.canopy.event, e] as const))(
    'recovers the original canopy frame for %s',
    (_name, entry) => {
      expect(roundTrip(entry)).toEqual([entry.canopy])
    },
  )
})

describe('the reducer cannot tell which protocol it was fed', () => {
  /** The property that actually matters: a client reading AG-UI must end up in
   *  exactly the state a client reading canopy's own frames ends up in. Field
   *  equality per frame is necessary but not sufficient — ordering and the
   *  reducer's own dedupe are where a subtle difference would show. */
  function reduceAll(frames: WsEvent[]): SessionState {
    const initial: SessionState = {
      messages: [],
      active_draft: null,
      participants: [],
      presence_user_ids: [],
      current_user_id: 0,
    }
    return frames.reduce(sessionReducer, initial)
  }

  it('reaches identical state via canopy frames and via AG-UI', () => {
    // Time is frozen because the reducer stamps `created_at`/`started_at` with
    // the wall clock as it runs, so two reductions a millisecond apart differ
    // in a field that has nothing to do with the protocol. Without this the
    // test fails intermittently for a reason that would send the next reader
    // hunting a mapping bug that is not there.
    vi.useFakeTimers()
    vi.setSystemTime(new Date('2026-09-15T12:00:00Z'))
    try {
      const direct = entries.map((e) => e.canopy)
      const viaAgui = entries.flatMap(roundTrip)

      expect(reduceAll(viaAgui)).toEqual(reduceAll(direct))
    } finally {
      vi.useRealTimers()
    }
  })

  it('and that state is not vacuously empty', () => {
    // Guard: if the fixture stopped producing messages this test would pass
    // while comparing nothing to nothing.
    expect(reduceAll(entries.map((e) => e.canopy)).messages.length).toBeGreaterThan(0)
  })
})

describe('a tool call spans three events, so it is assembled not truncated', () => {
  it('emits nothing until the arguments arrive', () => {
    // canopy carries a tool's input on one frame; AG-UI streams it on the ARGS
    // event that follows. Emitting on START would render a tool row with no
    // input — the half-empty tool call the ACP notes warn about.
    const start = fromAgui({
      type: 'TOOL_CALL_START',
      toolCallId: 't1',
      toolCallName: 'list_insights',
    })

    expect(start).toEqual([])
  })

  it('restores the runner’s own block verbatim', () => {
    // canopy passes the block straight through from the transcript and never
    // interprets it, so its shape belongs to the PRODUCER — Anthropic's on the
    // laptop, the cloud runner's over ACP. Rebuilding one from the AG-UI fields
    // would invent an `id` and a `type` that the real payload may not have had,
    // and hand the renderer something no runner ever sent.
    const block = { type: 'tool_use', id: 'toolu_01ABC', name: 'list_insights', input: { limit: 5 } }
    fromAgui({
      type: 'TOOL_CALL_START',
      toolCallId: 't1',
      toolCallName: 'list_insights',
      parentMessageId: 'm1',
      metadata: { canopy: { turn_index: 5, block } },
    })

    const [frame] = fromAgui({ type: 'TOOL_CALL_ARGS', toolCallId: 't1', delta: '{"limit":5}' })

    expect(frame).toEqual({
      event: 'chat.tool_use',
      data: {
        parent_message_id: 'm1',
        tool_message_id: 't1',
        turn_index: 5,
        block,
      },
    })
  })

  it('falls back to the protocol’s own fields for a non-canopy producer', () => {
    // An AG-UI stream from something that is not canopy carries no block. The
    // row is still renderable from name + arguments, which is the minimum the
    // protocol guarantees — better than dropping the call entirely.
    fromAgui({ type: 'TOOL_CALL_START', toolCallId: 't1', toolCallName: 'search' })
    const [frame] = fromAgui({ type: 'TOOL_CALL_ARGS', toolCallId: 't1', delta: '{"q":"x"}' })

    expect((frame.data as unknown as { block: unknown }).block).toEqual({ name: 'search', input: { q: 'x' } })
  })

  it('ignores arguments for a call it never saw start', () => {
    // A reconnect mid-call, or a stream that began before this client attached.
    expect(fromAgui({ type: 'TOOL_CALL_ARGS', toolCallId: 'unknown', delta: '{}' })).toEqual([])
  })

  it('does not carry a half-read call across a reconnect', () => {
    fromAgui({ type: 'TOOL_CALL_START', toolCallId: 't1', toolCallName: 'x' })
    resetAguiState()

    expect(fromAgui({ type: 'TOOL_CALL_ARGS', toolCallId: 't1', delta: '{}' })).toEqual([])
  })

  it('survives malformed arguments with an empty input rather than no row', () => {
    fromAgui({ type: 'TOOL_CALL_START', toolCallId: 't1', toolCallName: 'x' })
    const [frame] = fromAgui({ type: 'TOOL_CALL_ARGS', toolCallId: 't1', delta: 'not json' })

    expect((frame.data as unknown as { block: { input: unknown } }).block.input).toEqual({})
  })
})

describe('the blocked agent survives the trip', () => {
  const INTERRUPT = {
    type: 'RUN_FINISHED',
    threadId: 't1',
    runId: 'r1',
    outcome: {
      type: 'interrupt',
      interrupts: [
        {
          id: 'i1',
          reason: 'transcript',
          message: 'Phase gate',
          expiresAt: '2026-09-15T10:00:00+00:00',
          metadata: {
            canopy: {
              body: 'Phase 4 is test-gated.',
              questions: [
                {
                  index: 0,
                  question: 'Proceed?',
                  multi_select: false,
                  options: [{ number: 1, label: 'Yes' }],
                },
              ],
            },
          },
        },
      ],
    },
  }

  it('becomes a canopy menu a client can render', () => {
    const [frame] = fromAgui(INTERRUPT)
    const menu = (frame.data as unknown as { menu: Record<string, unknown> }).menu

    expect(frame.event).toBe('session.menu')
    expect(menu.question).toBe('Proceed?')
    // The body is often the only thing that makes a dialog answerable away from
    // the keyboard: "Do you want to proceed?" says nothing without it.
    expect(menu.body).toBe('Phase 4 is test-gated.')
  })

  it('keeps every question, not only the first', () => {
    // The TUI draws them as tabs and will not submit until each has an answer,
    // so a client showing one cannot complete the ask however it is pressed.
    const [frame] = fromAgui(INTERRUPT)
    const menu = (frame.data as unknown as { menu: { questions: unknown[] } }).menu

    expect(menu.questions).toHaveLength(1)
  })

  it('carries the staleness back as observed_at', () => {
    const [frame] = fromAgui(INTERRUPT)
    const menu = (frame.data as unknown as { menu: { observed_at: number } }).menu

    expect(menu.observed_at).toBe(Date.parse('2026-09-15T10:00:00+00:00') / 1000)
  })

  it('retracts a menu when someone answered at the keyboard', () => {
    const [frame] = fromAgui({ type: 'CUSTOM', name: 'canopy.menu.retracted', value: {} })

    expect(frame).toEqual({ event: 'session.menu', data: { menu: null } })
  })
})

describe('stopping is not erroring', () => {
  it('reads a cancelled run as a cancelled stream', () => {
    const [frame] = fromAgui({
      type: 'RUN_FINISHED',
      threadId: 't1',
      runId: 'r1',
      result: { cancelled: true, partial_len: 12 },
    })

    expect(frame.event).toBe('chat.stream_cancelled')
  })

  it('reads a plain finish as nothing at all', () => {
    // canopy has no frame for "the run ended cleanly" — the stream_complete
    // already said so. Inventing one would double-count the turn.
    expect(fromAgui({ type: 'RUN_FINISHED', threadId: 't1', runId: 'r1' })).toEqual([])
  })
})

describe('an unknown event cannot break a client', () => {
  it('ignores an event type this version has never heard of', () => {
    // AG-UI is 0.x and gains event types. A client that throws on one it does
    // not know is a client that breaks on the protocol improving.
    expect(fromAgui({ type: 'SOMETHING_NEW_IN_1_0', foo: 1 })).toEqual([])
  })

  it('ignores a CUSTOM event from someone else’s namespace', () => {
    expect(fromAgui({ type: 'CUSTOM', name: 'vendor.thing', value: {} })).toEqual([])
  })

  it.each([{}, { type: null }, { type: 'TEXT_MESSAGE_CONTENT' }])(
    'does not throw on malformed input %#',
    (frame) => {
      expect(() => fromAgui(frame as Record<string, unknown>)).not.toThrow()
    },
  )
})

describe('the socket actually asks for it', () => {
  /** A pure module nothing calls is a design document with a test suite — the
   *  mistake `apps/mcp/page_tools.py` made expensive once. These assert the
   *  option reaches the URL and the message handler, not just that the mapping
   *  is correct in isolation. */
  it('is wired to the hook’s public option', () => {
    const source = hookSource()

    // NOT `expect(source).toContain('protocol=ag-ui')`, which this used to say.
    // It held the whole time the flag was being dropped by any URL builder that
    // ignores its path — i.e. by canopy-web's widget and by ace-web. Whether the
    // flag reaches the socket is asserted where it can be seen, against the URL
    // a socket really opens: `useSessionSocket.protocol.test.tsx`.
    expect(source).toContain('fromAgui')
    // And the default stays canopy's own vocabulary, which is what lets an
    // existing consumer — ace-web installs this package from npm — notice
    // nothing at all.
    expect(source).toContain('protocol = "canopy"')
  })

  it('clears half-read state when it opens a connection', () => {
    // Tool-call ids are per-stream, so an ARGS event from a new connection must
    // not complete a call the previous one left open. The BEHAVIOUR is tested
    // directly above ("does not carry a half-read call across a reconnect");
    // what is checked here is that `connect` actually calls it, which no
    // behavioural test of the pure module can see.
    const connectBody = hookSource().slice(hookSource().indexOf('const connect ='))

    expect(connectBody).toContain('resetAguiState()')
  })
})
