# Generated by Django 6.1.1 on 2026-09-19 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("harness", "0043_turn_initiator"),
        ("slack", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlackRelayPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seq", models.PositiveIntegerField()),
                ("channel_id", models.CharField(max_length=32)),
                ("slack_ts", models.CharField(blank=True, default="", max_length=32)),
                ("error", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "turn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slack_posts",
                        to="harness.turn",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("turn", "seq"), name="slack_relay_once_per_row"
                    )
                ],
            },
        ),
    ]
