# Generated by Django 6.1.1 on 2026-09-19 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canopy_sessions", "0027_session_page_state"),
        ("slack", "0002_relay_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlackMenuPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64)),
                ("slack_ts", models.CharField(blank=True, default="", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slack_menu_posts",
                        to="canopy_sessions.session",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "key"), name="slack_menu_once_per_question"
                    )
                ],
            },
        ),
    ]
