# Generated by Django 6.1.1 on 2026-09-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0003_menu_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="slackmenupost",
            name="channel_id",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="slackmenupost",
            name="question",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="slackmenupost",
            name="resolved",
            field=models.BooleanField(default=False),
        ),
    ]
