# Generated by Django 6.1.1 on 2026-09-19 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("harness", "0043_turn_initiator"),
        ("slack", "0004_menu_post_buttons"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlackTurnPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_id", models.CharField(max_length=32)),
                ("slack_ts", models.CharField(blank=True, default="", max_length=32)),
                ("rendered", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "turn",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slack_status",
                        to="harness.turn",
                    ),
                ),
            ],
        ),
    ]
