# Generated by Django 6.1.1 on 2026-09-19 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canopy_sessions", "0027_session_page_state"),
        ("harness", "0043_turn_initiator"),
        ("slack", "0004_menu_post_buttons"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlackThreadStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_id", models.CharField(max_length=32)),
                ("slack_ts", models.CharField(blank=True, default="", max_length=32)),
                ("rendered", models.CharField(blank=True, default="", max_length=64)),
                ("episode", models.CharField(blank=True, default="", max_length=64)),
                ("notice_ts", models.CharField(blank=True, default="", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notice_runner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="harness.runner",
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slack_status",
                        to="canopy_sessions.session",
                    ),
                ),
            ],
        ),
    ]
