# Generated by Django 6.1.1 on 2026-09-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0005_turn_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="slackturnpost",
            name="offline_notice_ts",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
