# Generated by Django 6.1.1 on 2026-09-19 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canopy_sessions", "0027_session_page_state"),
        ("slack", "0006_turn_post_offline_notice"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlackTranscriptPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.BigIntegerField()),
                ("slack_ts", models.CharField(blank=True, default="", max_length=32)),
                ("error", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slack_transcript_posts",
                        to="canopy_sessions.session",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "index"), name="slack_transcript_post_once"
                    )
                ],
            },
        ),
    ]
