# Generated by Django 6.1.1 on 2026-09-19 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0007_transcript_post"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="slackinstallation",
            name="app_id",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="slackinstallation",
            name="commands_sync_error",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="slackinstallation",
            name="commands_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="slackinstallation",
            name="config_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="slackinstallation",
            name="config_refresh_enc",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="slackinstallation",
            name="config_set_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="slackinstallation",
            name="config_token_enc",
            field=models.TextField(blank=True, default=""),
        ),
    ]
