# Generated by Django 6.1.1 on 2026-09-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0008_command_sync"),
    ]

    operations = [
        migrations.AddField(
            model_name="slackturnpost",
            name="prefix",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
    ]
