# Generated by Django 6.1.1 on 2026-09-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0009_status_prefix"),
    ]

    operations = [
        migrations.AddField(
            model_name="slackinstallation",
            name="agent_declared_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
