# Generated by Django 6.1.1 on 2026-09-22 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def link_existing(apps, schema_editor):
    """Each installation keeps serving the one workspace it served before."""
    Installation = apps.get_model("slack", "SlackInstallation")
    Link = apps.get_model("slack", "SlackWorkspaceLink")
    for inst in Installation.objects.all():
        Link.objects.get_or_create(workspace_id=inst.workspace_id,
                                   defaults={"installation": inst, "linked_by_id": inst.installed_by_id})


def unlink(apps, schema_editor):
    Installation = apps.get_model("slack", "SlackInstallation")
    Link = apps.get_model("slack", "SlackWorkspaceLink")
    for link in Link.objects.order_by("linked_at"):
        Installation.objects.filter(pk=link.installation_id, workspace__isnull=True) \
            .update(workspace_id=link.workspace_id)


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0010_agent_declared"),
        ("workspaces", "0008_rename_auto_join_domains_self_join_domains"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SlackWorkspaceLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="slack.slackinstallation",
                    ),
                ),
                (
                    "linked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slack_link",
                        to="workspaces.workspace",
                    ),
                ),
            ],
        ),
        migrations.RunPython(link_existing, unlink),
        migrations.RemoveField(
            model_name="slackinstallation",
            name="workspace",
        ),
    ]
