# Generated by Django 6.1.1 on 2026-09-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0011_workspace_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="slackworkspacelink",
            name="history_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="slackworkspacelink",
            name="history_max_minutes",
            field=models.PositiveIntegerField(default=120),
        ),
    ]
