# Generated by Django 6.1.1 on 2026-10-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0012_workspace_history_policy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slackturnpost",
            name="prefix",
            field=models.TextField(blank=True, default=""),
        ),
    ]
