# Generated by Django 5.2.12 on 2026-07-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_agent_workspace_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='turn_mode',
            field=models.CharField(choices=[('gated', 'gated (outbound waits for human approval)'), ('auto', 'auto (self-review-and-send, audit on the board)')], default='gated', max_length=8),
        ),
    ]
