# Generated by Django 5.2.12 on 2026-08-11 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # Never before the reports have been copied onto harness.Turn.
        ('agents', '0016_agentturn_into_harness_turn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgentTurn',
        ),
    ]
