# Generated by Django 5.2.12 on 2026-09-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0018_agent_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='op_sa_token_enc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agent',
            name='op_vault',
            field=models.CharField(blank=True, default='', help_text="1Password vault holding this agent's secrets, e.g. Agent-Ace.", max_length=200),
        ),
        migrations.AddField(
            model_name='agent',
            name='runtime_sources',
            field=models.JSONField(blank=True, default=dict, help_text='Per-ref value source from runtime.yaml: {"name": {"op": "op://..."}} or {"name": {"value": "literal"}}. Never holds a secret VALUE for an op-backed ref — only where to find it.'),
        ),
    ]
