# Generated by Django 5.2.12 on 2026-09-07 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0019_agent_op_sa_token_enc_agent_op_vault_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentBootstrapReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runner_name', models.CharField(max_length=200)),
                ('client_creds_ok', models.BooleanField(default=False)),
                ('mailbox_ok', models.BooleanField(default=False)),
                ('gog_client', models.CharField(blank=True, default='', max_length=120)),
                ('detail', models.TextField(blank=True, default='')),
                ('reported_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bootstrap_reports', to='agents.agent')),
            ],
            options={
                'ordering': ['agent_id', 'runner_name'],
                'constraints': [models.UniqueConstraint(fields=('agent', 'runner_name'), name='uniq_bootstrap_report_per_agent_runner')],
            },
        ),
    ]
