# Generated by Django 5.2.12 on 2026-09-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0020_agentbootstrapreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentbootstrapreport',
            name='turn_client',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='agentbootstrapreport',
            name='turn_ready',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
