# Generated by Django 5.2.12 on 2026-09-16 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0021_bootstrap_report_turn_client"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    def backfill(apps, schema_editor):
        """Link each agent to the login that already carries its mailbox.

        Exact, non-blank email match, and only when it resolves to exactly ONE
        user — an ambiguous match is left NULL rather than guessed at, because
        the whole point of this column is to stop authorization resting on a
        field that can collide.
        """
        Agent = apps.get_model("agents", "Agent")
        User = apps.get_model("auth", "User")
        linked = 0
        for agent in Agent.objects.exclude(email="").filter(user__isnull=True):
            matches = list(User.objects.filter(email__iexact=agent.email)[:2])
            if len(matches) == 1:
                agent.user = matches[0]
                agent.save(update_fields=["user"])
                linked += 1
        print(f"  agents.0022: linked {linked} agent(s) to their own login")

    operations = [
        migrations.AddField(
            model_name="agent",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="The agent's own canopy login, used when it calls canopy as itself.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_identity",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
