# Generated by Django 6.1.1 on 2026-09-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0022_agent_user_identity"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="slack_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
