# Generated by Django 6.1.1 on 2026-09-18 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0023_agent_slack_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillHistoryCommit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sha", models.CharField(max_length=64)),
                ("committed_at", models.DateTimeField()),
                ("subject", models.TextField()),
                ("body", models.TextField(blank=True, default="")),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_history_commits",
                        to="agents.agent",
                    ),
                ),
            ],
            options={
                "ordering": ["committed_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="SkillHistorySync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("head_sha", models.CharField(blank=True, default="", max_length=64)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "synced_with",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("last_error", models.TextField(blank=True, default="")),
                ("last_state", models.CharField(blank=True, default="", max_length=32)),
                ("sync_started_at", models.DateTimeField(blank=True, null=True)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("groups", models.JSONField(blank=True, default=list)),
                ("checks", models.JSONField(blank=True, default=dict)),
                ("present", models.JSONField(blank=True, default=list)),
                (
                    "agent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_history_sync",
                        to="agents.agent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SkillRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill", models.CharField(max_length=120)),
                ("lines_after", models.IntegerField()),
                ("added", models.IntegerField()),
                ("deleted", models.IntegerField()),
                (
                    "commit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="agents.skillhistorycommit",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="skillhistorycommit",
            constraint=models.UniqueConstraint(
                fields=("agent", "sha"), name="uniq_agent_skill_history_sha"
            ),
        ),
        migrations.AddIndex(
            model_name="skillrevision",
            index=models.Index(fields=["skill"], name="agents_skil_skill_32ee0d_idx"),
        ),
    ]
