# Generated by Django 6.1.1 on 2026-09-20 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0024_skill_history"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ext_id",
                    models.CharField(
                        help_text="Stable id, unique per agent (P1, P2 …).",
                        max_length=64,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="What the project is called — and its Drive folder's name.",
                        max_length=200,
                    ),
                ),
                (
                    "outcome",
                    models.TextField(
                        blank=True, default="", help_text="What done looks like."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("done", "Done"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "owner_note",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "drive_folder_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "drive_folder_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("repo_slug", models.CharField(blank=True, default="", max_length=100)),
                ("notes", models.TextField(blank=True, default="")),
                ("links", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="agents.agent",
                    ),
                ),
                (
                    "owner_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["status", "-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="agenttask",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="agents.agentproject",
            ),
        ),
        migrations.AddIndex(
            model_name="agentproject",
            index=models.Index(
                fields=["agent", "status"], name="agents_agen_agent_i_6bc284_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="agentproject",
            constraint=models.UniqueConstraint(
                fields=("agent", "ext_id"), name="agent_project_ext_id_unique"
            ),
        ),
    ]
