# Generated by Django 6.1.1 on 2026-09-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0025_agent_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="project_seq",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
