# Generated by Django 6.1.1 on 2026-09-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0027_task_absorbs_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="task_seq",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
