# Generated by Django 6.1.1 on 2026-09-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0028_agent_task_seq"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenttask",
            name="ask_dismissed",
            field=models.BooleanField(default=False),
        ),
    ]
