# Generated by Django 6.1.1 on 2026-09-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0032_declared_interface"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="interface_source",
            field=models.TextField(blank=True, default=""),
        ),
    ]
