# Generated by Django 6.1.1 on 2026-09-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0033_interface_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentbootstrapreport",
            name="env_ok",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
