# Generated by Django 6.1.1 on 2026-10-06 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0035_agent_delegation"),
    ]

    operations = [
        migrations.CreateModel(
            name="RepoIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "repo_slug",
                    models.CharField(
                        help_text="The repo name a project turn carries in Turn.project (e.g. canopy-web).",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        help_text="The agent whose owner's GitHub delegation the repo's agentless turns use.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repo_identities",
                        to="agents.agent",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "repo identities",
                "ordering": ["repo_slug"],
            },
        ),
    ]
