# Generated by Django 6.1.1 on 2026-10-08 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0038_projects_and_tasks_final_shape"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentdelegation",
            name="lender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lent_delegations",
                to="agents.agent",
            ),
        ),
        migrations.AlterField(
            model_name="agentdelegation",
            name="secret_enc",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="agentdelegation",
            name="service",
            field=models.CharField(
                choices=[("github", "GitHub"), ("salesforce", "Salesforce")],
                max_length=32,
            ),
        ),
    ]
