# Generated by Django 6.1.1 on 2026-10-08 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0039_agent_delegation_salesforce_lender"),
        ("contacts", "0010_people_brain_v11"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="people_digest_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="ProjectParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(blank=True, default="", max_length=80)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("fact", "A fact about them was filed against the project"),
                            (
                                "turn",
                                "A conversation with them raised one of its tasks",
                            ),
                            ("manual", "Added by a person"),
                        ],
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_participations",
                        to="contacts.person",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant_rows",
                        to="agents.agentproject",
                    ),
                ),
            ],
            options={
                "db_table": "agents_project_participant",
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.AddField(
            model_name="agentproject",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="agent_projects",
                through="agents.ProjectParticipant",
                to="contacts.person",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectparticipant",
            constraint=models.UniqueConstraint(
                fields=("project", "person"), name="one_participant_row_per_person"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectparticipant",
            constraint=models.CheckConstraint(
                condition=models.Q(("source__in", ["fact", "turn", "manual"])),
                name="project_participant_source_known",
            ),
        ),
    ]
