# Generated by Django 6.1.1 on 2026-10-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0041_link_fact_subjects_to_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="ship_repos",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
