# Generated by Django 6.1.1 on 2026-10-09 14:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0043_task_action_nudge"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="people_digest_enabled",
        ),
    ]
