# Generated by Django 6.1.1 on 2026-10-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0044_remove_people_digest"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="credential_source",
            field=models.CharField(
                choices=[
                    ("1password", "1Password (op, via the agent's vault key)"),
                    ("canopy-web", "canopy-web (AgentCredential values)"),
                ],
                default="1password",
                max_length=16,
            ),
        ),
    ]
