# Generated by Django 6.1.1 on 2026-10-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walkthroughs", "0008_mint_share_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="walkthrough",
            name="cut_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="walkthrough",
            name="cut_scene_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
