# Generated by Django 6.1.1 on 2026-10-05 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agents", "0035_agent_delegation"),
        ("workspaces", "0012_access_requests"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RetentionSweep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "applied",
                    models.BooleanField(
                        default=False, help_text="False = dry run; nothing was deleted."
                    ),
                ),
                ("trigger", models.CharField(default="command", max_length=16)),
                ("counts", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="RetentionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("chat", "Chat: a conversation and every turn on it"),
                            ("turn", "Turn: agent/project work that is not a chat"),
                            (
                                "shared",
                                "Shared transcript: an uploaded /canopy:share-session",
                            ),
                        ],
                        default="",
                        max_length=8,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("api", "API"),
                            ("ace_web", "ace-web"),
                            ("canopy_web_chat", "canopy-web chat"),
                            ("canopy_scheduler", "canopy scheduler"),
                            ("email", "Email"),
                            ("slack", "Slack"),
                            ("emdash", "emdash (runner-discovered chat)"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                (
                    "principal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("member", "Member: a canopy user"),
                            ("contact", "Contact: an outside person with no account"),
                            ("agent", "Agent: another agent dispatched it"),
                            (
                                "system",
                                "System: a schedule, a drill, or nobody established",
                            ),
                        ],
                        default="",
                        max_length=8,
                    ),
                ),
                (
                    "keep_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Drop matching content this many days after it was written. Blank = keep forever.",
                        null=True,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, default="", help_text="Why this rule exists."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retention_rules",
                        to="agents.agent",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retention_rules",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["workspace_id", "kind", "source", "principal"],
            },
        ),
    ]
