# Generated by Django 5.2.12 on 2026-07-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canopy_sessions', '0012_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
