# Generated by Django 5.2.12 on 2026-07-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canopy_sessions', '0013_attachment_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='ordinal_scheme',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
