# Generated by Django 5.2.12 on 2026-07-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canopy_sessions', '0014_session_ordinal_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='runnerbinding',
            name='pending_question',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
