# Generated by Django 5.2.12 on 2026-07-31 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canopy_sessions', '0014_session_ordinal_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='runnerbinding',
            name='reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
