# Generated by Django 5.2.12 on 2026-07-31 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canopy_sessions', '0015_runnerbinding_pending_question'),
        ('canopy_sessions', '0015_runnerbinding_reported_at'),
    ]

    operations = [
    ]
