# Generated by Django 5.2.12 on 2026-08-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canopy_sessions', '0016_merge_20260731_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='runnerbinding',
            name='pending_answer',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
