# Generated by Django 5.2.12 on 2026-08-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canopy_sessions', '0017_pending_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='runnerbinding',
            name='close_requested',
            field=models.BooleanField(default=False),
        ),
    ]
