# Generated by Django 5.2.12 on 2026-08-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canopy_sessions', '0018_close_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='runnerbinding',
            name='agent_status',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
