# Generated by Django 5.2.12 on 2026-08-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canopy_sessions', '0019_runnerbinding_agent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='runnerbinding',
            name='transcript_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
