# Generated by Django 5.2.12 on 2026-09-12 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canopy_sessions', '0023_backfill_runner_session_agent_and_tenant'),
        ('harness', '0042_runneradmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='runnerbinding',
            name='index_offset',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='runnerbinding',
            name='transferred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runnerbinding',
            name='transferred_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_bindings_transferred_away', to='harness.runner'),
        ),
    ]
