# Generated by Django 5.2.12 on 2026-09-13 20:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canopy_sessions', '0024_session_transfer_epoch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='page_actions_available',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='PageAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('args', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('result', models.JSONField(blank=True, default=None, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('requested_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_actions', to='canopy_sessions.session')),
            ],
            options={
                'db_table': 'session_page_actions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'status'], name='session_pag_session_54c7cd_idx')],
            },
        ),
    ]
