# Generated by Django 5.2.12 on 2026-09-14 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canopy_sessions', '0025_session_page_actions_available_pageaction'),
        ('contacts', '0002_contact_beyond_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='contacts.contact'),
        ),
    ]
