# Generated by Django 6.1.1 on 2026-09-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canopy_sessions", "0027_session_page_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="finish_push_due_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="notify_every_completion",
            field=models.BooleanField(default=False),
        ),
    ]
