# Generated by Django 6.1.1 on 2026-09-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canopy_sessions", "0028_session_finish_push_due_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="runnerbinding",
            name="missed_reports",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
