# Generated by Django 6.1.1 on 2026-09-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canopy_sessions", "0032_chat_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="author",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="source_turn_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
