# Generated by Django 6.1.1 on 2026-09-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canopy_sessions", "0034_draft_per_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="draft",
            name="visibility",
            field=models.CharField(
                choices=[("live", "Live"), ("typing", "Typing"), ("hidden", "Hidden")],
                default="live",
                max_length=8,
            ),
        ),
    ]
