# Generated by Django 6.1.1 on 2026-10-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canopy_sessions", "0039_retitle_command_named_sessions"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="content_purged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="retention_floor_index",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
