# Generated by Django 6.1.1 on 2026-10-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canopy_sessions", "0041_session_provenance"),
    ]

    operations = [
        migrations.AddField(
            model_name="runnerbinding",
            name="task_uid",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
