# Generated by Django 6.1.1 on 2026-10-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canopy_sessions", "0042_runnerbinding_task_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="activity",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="session",
            name="activity_keys",
            field=models.TextField(blank=True, default=""),
        ),
    ]
