# Generated by Django 5.2.12 on 2026-07-26 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0003_appcredential_provision_role_and_more'),
        ('workspaces', '0002_workspaceinvite_uniq_ws_invite_live_per_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemembership',
            name='provisioned_by_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisioned_memberships', to='tokens.appcredential'),
        ),
    ]
