# Generated by Django 5.2.12 on 2026-07-26 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0004_appcredential_provision_role_allowlist'),
        ('workspaces', '0003_workspacemembership_provisioned_by_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacemembership',
            name='provisioned_by_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provisioned_memberships', to='tokens.appcredential'),
        ),
    ]
