# Generated by Django 5.2.12 on 2026-07-28 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    """Charset validator on Workspace.slug — see models.SLUG_PATTERN.

    Validators-only: no DDL, no data touched. Deliberately NOT a data
    migration — if a pre-existing row violates the new charset it is reported
    and decided on by a human, never silently renamed (a slug is a primary key
    and an addressing token; rewriting one re-homes every URL that points at
    it).
    """

    dependencies = [
        ('workspaces', '0004_provisioned_by_app_protect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='slug',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_slug', message='Slug must start with a lowercase letter or digit and contain only lowercase letters, digits and hyphens.', regex='^[a-z0-9][a-z0-9-]*$')]),
        ),
    ]
