# Generated by Django 5.2.12 on 2026-07-28 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_alter_workspace_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='slug',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_slug', message='Slug must start with a lowercase letter or digit and contain only lowercase letters, digits and hyphens.', regex='^[a-z0-9][a-z0-9-]*\\Z')]),
        ),
    ]
