# Generated by Django 5.2.12 on 2026-09-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_alter_workspace_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='shared_op_sa_token_enc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workspace',
            name='shared_op_vault',
            field=models.CharField(blank=True, default='', help_text='1Password vault holding secrets every agent in this workspace needs, e.g. Canopy-Shared. Blank falls back to the box default.', max_length=200),
        ),
    ]
