# Generated by Django 6.1.1 on 2026-09-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0008_rename_auto_join_domains_self_join_domains"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspaceinvite",
            name="last_emailed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
