# Generated by Django 6.1.1 on 2026-09-29 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0009_invite_last_emailed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="workspaces.workspace",
            ),
        ),
    ]
