# Generated by Django 6.1.1 on 2026-10-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0010_workspace_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspaceinvite",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Admin"),
                    ("editor", "Editor"),
                    ("viewer", "Viewer"),
                ],
                default="editor",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="workspacemembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Admin"),
                    ("editor", "Editor"),
                    ("viewer", "Viewer"),
                ],
                max_length=16,
            ),
        ),
    ]
