# Generated by Django 6.1.1 on 2026-10-08 05:05

import apps.threads.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workspaces", "0013_system_accounts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentThread",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.threads.models.new_thread_id,
                        editable=False,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(max_length=40)),
                ("purpose", models.CharField(max_length=300)),
                ("participants", models.JSONField(default=list)),
                ("moderator", models.CharField(max_length=80)),
                ("parent", models.JSONField(blank=True, default=dict)),
                ("context", models.TextField(blank=True, default="")),
                ("max_messages", models.PositiveSmallIntegerField(default=4)),
                ("deadline_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("settled", "Settled"),
                            ("out_of_budget", "Out of budget"),
                            ("timed_out", "Timed out"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("outcome", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_threads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_threads",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "status", "-created_at"],
                        name="threads_age_workspa_b7e632_idx",
                    )
                ],
            },
        ),
    ]
