# Generated by Django 5.2.12 on 2026-07-24 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_agent_runner_preference'),
        ('harness', '0022_delete_sessionlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='pinned_runner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_turns', to='harness.runner'),
        ),
        migrations.AlterField(
            model_name='item',
            name='origin',
            field=models.CharField(choices=[('board', 'Board'), ('api', 'API'), ('slack', 'Slack'), ('cron', 'Cron'), ('manual', 'Manual'), ('email', 'Email'), ('drill', 'Drill')], max_length=10),
        ),
        migrations.AlterField(
            model_name='turn',
            name='origin',
            field=models.CharField(choices=[('board', 'Board'), ('api', 'API'), ('slack', 'Slack'), ('cron', 'Cron'), ('manual', 'Manual'), ('email', 'Email'), ('drill', 'Drill')], max_length=10),
        ),
        migrations.CreateModel(
            name='RunnerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runner_assignments', to='agents.agent')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_assignments', to='harness.runner')),
            ],
            options={
                'ordering': ['agent_id', 'rank'],
                'constraints': [models.UniqueConstraint(fields=('agent', 'runner'), name='one_assignment_per_agent_runner')],
            },
        ),
        migrations.CreateModel(
            name='RunnerDrill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('pass', 'Pass'), ('fail', 'Fail')], default='pending', max_length=8)),
                ('summary', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runner_drills', to='agents.agent')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drills', to='harness.runner')),
                ('turn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='harness.turn')),
            ],
            options={
                'ordering': ['agent__slug'],
                'constraints': [models.UniqueConstraint(fields=('runner', 'agent'), name='one_drill_row_per_runner_agent')],
            },
        ),
    ]
