# Generated by Django 5.2.12 on 2026-07-24 23:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harness', '0024_seed_runner_assignments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runnerdrill',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
