# Generated by Django 5.2.12 on 2026-07-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harness', '0025_alter_runnerdrill_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='runnerassignment',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
