# Generated by Django 5.2.12 on 2026-07-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harness', '0026_runnerassignment_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turn',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('claimed', 'Claimed'), ('running', 'Running'), ('needs_human', 'Needs human'), ('done', 'Done'), ('failed', 'Failed'), ('lost', 'Lost'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='queued', max_length=12),
        ),
    ]
