# Generated by Django 5.2.12 on 2026-07-26 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harness', '0027_alter_turn_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_jsonl_gz', models.BinaryField()),
                ('line_count', models.PositiveIntegerField(default=0)),
                ('bytes_raw', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('turn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='harness.turn')),
            ],
        ),
    ]
