# Generated by Django 5.2.12 on 2026-07-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harness', '0028_turntranscript'),
    ]

    operations = [
        migrations.AddField(
            model_name='turntranscript',
            name='last_batch_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='turntranscript',
            name='truncated',
            field=models.BooleanField(default=False),
        ),
    ]
