# Generated by Django 5.2.12 on 2026-07-29 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harness', '0031_runnerassignment_source_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='code_sha',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='runner',
            name='code_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
