# Generated by Django 5.2.12 on 2026-07-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harness', '0032_runner_code_provenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='code_committed_at',
            field=models.BigIntegerField(default=0),
        ),
    ]
