# Generated by Django 5.2.12 on 2026-07-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harness', '0033_runner_code_committed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='paused',
            field=models.BooleanField(default=False, help_text='Operator pause: the runner stays live but claims nothing.'),
        ),
        migrations.AddField(
            model_name='runner',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runner',
            name='paused_note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='runner',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('stale', 'Stale'), ('disconnected', 'Disconnected'), ('degraded', 'Degraded'), ('retired', 'Retired'), ('paused', 'Paused')], default='disconnected', max_length=12),
        ),
    ]
