# Generated by Django 5.2.12 on 2026-07-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harness', '0034_runner_paused_runner_paused_at_runner_paused_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='sessions_reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
