# Generated by Django 5.2.12 on 2026-08-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harness', '0035_runner_sessions_reported_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='runnercredential',
            name='claude_api_key_enc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='runnercredential',
            name='claude_token_secondary_enc',
            field=models.TextField(blank=True, default=''),
        ),
    ]
