# Generated by Django 5.2.12 on 2026-08-11 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canopy_sessions', '0018_close_requested'),
        ('harness', '0036_runnercredential_claude_api_key_enc_and_more'),
        ('workspaces', '0006_alter_workspace_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='cli_session_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='turn',
            name='emdash_task_id',
            field=models.CharField(blank=True, default='', help_text='The emdash task/session this turn drove — the close-out join key.', max_length=200),
        ),
        migrations.AddField(
            model_name='turn',
            name='report_source',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='turn',
            name='report_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='turn',
            name='report_title',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='turn',
            name='reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turn',
            name='session_slug',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='turn',
            name='share_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='turn',
            name='task_ext_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='turn',
            name='work_product_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='turn',
            index=models.Index(fields=['agent', 'emdash_task_id'], name='harness_tur_agent_i_984782_idx'),
        ),
        migrations.AddConstraint(
            model_name='turn',
            constraint=models.UniqueConstraint(condition=models.Q(('cli_session_id', ''), _negated=True), fields=('agent', 'cli_session_id'), name='uniq_turn_agent_cli_session'),
        ),
    ]
