# Generated by Django 5.2.12 on 2026-09-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harness', '0038_turn_agent_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Sessionless retries so far — see services.MAX_SESSIONLESS_RETRIES.'),
        ),
    ]
