# Generated by Django 5.2.12 on 2026-09-08 16:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harness', '0040_actor_runner_routing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RunnerMint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('requested', 'requested'), ('awaiting_code', 'awaiting code'), ('completing', 'completing'), ('done', 'done'), ('failed', 'failed')], default='requested', max_length=16)),
                ('authorize_url', models.TextField(blank=True, default='')),
                ('code', models.TextField(blank=True, default='')),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mints', to='harness.runner')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['runner', '-created_at'], name='harness_run_runner__67cde6_idx')],
            },
        ),
    ]
