# Generated by Django 6.1.1 on 2026-09-20 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0027_task_absorbs_item"),
        ("harness", "0043_turn_initiator"),
    ]

    operations = [
        migrations.AddField(
            model_name="turn",
            name="raised_from_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dispatched_turns",
                to="agents.agenttask",
            ),
        ),
    ]
