# Generated by Django 6.1.1 on 2026-09-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("harness", "0044_turn_raised_from_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="turn",
            name="capability",
            field=models.CharField(blank=True, default="", max_length=48),
        ),
    ]
