# Generated by Django 6.1.1 on 2026-09-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("harness", "0045_declared_interface"),
    ]

    operations = [
        migrations.AddField(
            model_name="runner",
            name="health",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="runner",
            name="refresh_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
