# Generated by Django 6.1.1 on 2026-09-22 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canopy_sessions", "0028_session_finish_push_due_at_and_more"),
        ("harness", "0046_runner_health"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallerToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "chat_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caller_tokens",
                        to="canopy_sessions.session",
                    ),
                ),
                (
                    "turn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caller_tokens",
                        to="harness.turn",
                    ),
                ),
            ],
        ),
    ]
