# Generated by Django 6.1.1 on 2026-09-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("harness", "0048_agentschedule_always_run"),
    ]

    operations = [
        migrations.AddField(
            model_name="runnerassignment",
            name="turn_mode",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AddField(
            model_name="turn",
            name="turn_mode",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AddField(
            model_name="turn",
            name="turn_mode_basis",
            field=models.CharField(blank=True, default="", max_length=320),
        ),
    ]
