# Generated by Django 6.1.1 on 2026-09-24 00:06

"""Drop the `Item` tombstone and the `Turn.raised_from` edge that fed it.

#873 moved every item onto `AgentTask` (`ask_kind`/`ask_body`/`ask_state`/
`decision`…), keeping each item's id as the task's `uuid` so old links resolve,
and `harness.Item`'s docstring has said "Nothing reads this model" since. The
table was kept one release as the rollback path.

MEASURED ON LABS BEFORE DROPPING, because a table drop is not reversible:
  * 44 item rows, and all 44 have a task with the matching uuid — 0 orphans;
  * 4 turns carry `raised_from`, and 0 of them lack `raised_from_task`,
    so no provenance is only reachable through the edge being removed.
"""

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("harness", "0049_turn_mode_rules"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="item",
            name="harness_ite_agent_i_99d621_idx",
        ),
        migrations.RemoveIndex(
            model_name="item",
            name="harness_ite_state_01fe53_idx",
        ),
        migrations.RemoveField(
            model_name="turn",
            name="raised_from",
        ),
        migrations.DeleteModel(
            name="Item",
        ),
    ]
