# Generated by Django 6.1.1 on 2026-09-24 00:13

"""A cloud runner holds no 1Password key.

It had one — a box-wide service account, staged into the runner's own
environment. Every turn's env is built from that one, so each agent inherited a
credential that reads EVERY agent's vault: the bound `Agent.op_vault` exists to
keep, undone by inheritance. Agent and tenant keys are issued per agent at
bootstrap instead, so nothing reads this column.

The value is a copy of Secrets Manager's `canopy/cloud-runner/op-service-account-token`,
so dropping the column destroys no sole copy of anything.
"""

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("harness", "0050_drop_item_tombstone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="runnercredential",
            name="op_sa_token_enc",
        ),
    ]
