# Generated by Django 6.1.1 on 2026-09-24 22:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("harness", "0051_runner_holds_no_1password_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="runnercredential",
            name="github_token_enc",
        ),
    ]
