# Generated by Django 6.1.1 on 2026-09-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("harness", "0052_runner_holds_no_github_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="runnercredential",
            name="claude_token_label",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="runnercredential",
            name="claude_token_secondary_label",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="runnermint",
            name="slot",
            field=models.CharField(
                choices=[("primary", "primary"), ("secondary", "secondary")],
                default="primary",
                max_length=16,
            ),
        ),
    ]
