# Generated by Django 6.1.1 on 2026-09-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("harness", "0053_runner_login_labels_and_mint_slot"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentschedule",
            name="run_once_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Fire once at this instant, then disable. Null for a recurring schedule.",
                null=True,
            ),
        ),
    ]
