# Generated by Django 6.1.1 on 2026-10-02 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("harness", "0055_runnerflag"),
        ("workspaces", "0011_admin_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceRunnerOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.PositiveSmallIntegerField()),
                ("enabled", models.BooleanField(default=True)),
                (
                    "runner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_order_rows",
                        to="harness.runner",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runner_order",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["workspace_id", "rank"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "runner"),
                        name="one_order_row_per_workspace_runner",
                    )
                ],
            },
        ),
    ]
