# Generated by Django 6.1.1 on 2026-10-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("harness", "0059_rename_runner_paired_by_to_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="runner",
            name="mailboxes_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="runner",
            name="mailboxes_readable",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
