# Generated by Django 6.1.1 on 2026-10-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("harness", "0061_turn_requested_turn_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="turn",
            name="content_purged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
