# Generated by Django 6.1.1 on 2026-10-05 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0035_agent_delegation"),
        ("canopy_sessions", "0040_session_content_purged_at_and_more"),
        ("contacts", "0008_slack_member_grade"),
        ("harness", "0062_turn_content_purged_at"),
        ("workspaces", "0012_access_requests"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="turn",
            name="one_executing_turn_per_session",
        ),
        migrations.AddField(
            model_name="turn",
            name="rides_turn",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="riders",
                to="harness.turn",
            ),
        ),
        migrations.AddConstraint(
            model_name="turn",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("rides_turn__isnull", True),
                    ("status__in", ["claimed", "running", "needs_human"]),
                ),
                fields=("chat_session",),
                name="one_executing_turn_per_session",
            ),
        ),
    ]
