# Generated by Django 6.1.1 on 2026-10-06 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canopy_sessions", "0041_provenance"),
        ("harness", "0063_turn_rides_turn"),
    ]

    operations = [
        migrations.AddField(
            model_name="turn",
            name="parent_claude_session",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="turn",
            name="parent_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_turns",
                to="canopy_sessions.session",
            ),
        ),
        migrations.AddField(
            model_name="turn",
            name="parent_task",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="turn",
            name="parent_turn",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_turns",
                to="harness.turn",
            ),
        ),
        migrations.AddField(
            model_name="turn",
            name="provenance",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
