# Generated by Django 6.1.1 on 2026-10-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("harness", "0064_turn_provenance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runner",
            name="kind",
            field=models.CharField(
                choices=[
                    ("emdash", "Emdash"),
                    ("cloud", "Cloud"),
                    ("remote", "Remote"),
                    ("desktop", "Claude desktop"),
                ],
                max_length=10,
            ),
        ),
    ]
