# Generated by Django 6.1.1 on 2026-10-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("harness", "0065_runner_kind_desktop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runner",
            name="engine",
            field=models.CharField(
                choices=[("emdash", "emdash"), ("claude-desktop", "Claude desktop")],
                default="emdash",
                help_text="The agent engine this runner drives (not assumed to be emdash).",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="runner",
            name="kind",
            field=models.CharField(
                choices=[
                    ("emdash", "Emdash"),
                    ("cloud", "Cloud"),
                    ("remote", "Remote"),
                ],
                max_length=10,
            ),
        ),
    ]
