# Generated by Django 6.1.1 on 2026-10-07 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("harness", "0066_runner_engine_claude_desktop"),
        ("workspaces", "0013_system_accounts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FailureInvestigation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fingerprint", models.CharField(max_length=64, unique=True)),
                ("normalized_note", models.TextField(blank=True, default="")),
                ("sample_note", models.TextField(blank=True, default="")),
                ("first_seen", models.DateTimeField()),
                ("last_seen", models.DateTimeField()),
                ("occurrences", models.PositiveIntegerField(default=1)),
                ("turn_ids", models.JSONField(blank=True, default=list)),
                ("agents", models.JSONField(blank=True, default=list)),
                ("runners", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("held", "Held by the rate cap"),
                            ("debugger_failed", "Debug turn failed"),
                            ("resolved", "Resolved"),
                            ("escalated", "Escalated"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("recurred_after_resolve", models.BooleanField(default=False)),
                ("triggers", models.PositiveSmallIntegerField(default=0)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "debug_turn",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="investigations",
                        to="harness.turn",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failure_investigations",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen"],
                "indexes": [
                    models.Index(
                        fields=["status", "-last_seen"],
                        name="harness_fai_status_ce4dc4_idx",
                    )
                ],
            },
        ),
    ]
