# Generated by Django 6.1.1 on 2026-10-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("harness", "0068_fleethold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentschedule",
            name="routing",
            field=models.CharField(
                choices=[
                    ("prefer_local", "Prefer local"),
                    ("local_only", "Local only"),
                    ("any", "Any"),
                    ("cloud_only", "Cloud only"),
                ],
                default="prefer_local",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="turn",
            name="routing",
            field=models.CharField(
                choices=[
                    ("prefer_local", "Prefer local"),
                    ("local_only", "Local only"),
                    ("any", "Any"),
                    ("cloud_only", "Cloud only"),
                ],
                default="prefer_local",
                max_length=15,
            ),
        ),
    ]
