# Generated by Django 6.1.1 on 2026-10-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("harness", "0068_fleethold"),
    ]

    operations = [
        migrations.AddField(
            model_name="runner",
            name="unpause_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
