# Generated by Django 6.1.1 on 2026-10-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harness', '0069_runner_unpause_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='callertoken',
            name='scoped',
            field=models.BooleanField(default=False),
        ),
    ]
