# Generated by Django 5.2.12 on 2026-07-26 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0004_provisioned_by_app_protect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('prose', models.TextField(blank=True, default='')),
                ('position', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narrative_slug', models.CharField(max_length=200)),
                ('position', models.IntegerField(default=0)),
                ('pinned_run_id', models.CharField(blank=True, default='', max_length=200)),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='storyboards.act')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Storyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('lede', models.TextField(blank=True, default='')),
                ('share_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('capability', models.CharField(choices=[('read', 'Read only'), ('comment', 'Read + comment'), ('suggest', 'Read + comment + suggest edits')], default='read', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storyboards', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='act',
            name='storyboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='storyboards.storyboard'),
        ),
        migrations.AddConstraint(
            model_name='storyboard',
            constraint=models.UniqueConstraint(fields=('workspace', 'slug'), name='uniq_storyboard_workspace_slug'),
        ),
    ]
