# Generated by Django 5.2.12 on 2026-08-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboards', '0002_act_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='blurb',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='storyboard',
            name='layout',
            field=models.CharField(choices=[('review', 'Review — prose, scene links, notes'), ('reel', 'Reel — the videos and nothing else')], default='review', max_length=16),
        ),
    ]
