# Generated by Django 6.1.1 on 2026-10-09 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0045_agent_credential_source"),
        ("canopy_sessions", "0041_session_provenance"),
        ("harness", "0070_callertoken_scoped"),
        ("storyboards", "0004_backfill_feedback_workspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="storyboard",
            name="agent_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="agents.agentproject",
            ),
        ),
        migrations.AddField(
            model_name="storyboard",
            name="source_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="canopy_sessions.session",
            ),
        ),
        migrations.AddField(
            model_name="storyboard",
            name="source_turn",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="harness.turn",
            ),
        ),
    ]
