# Generated by Django 6.1.1 on 2026-10-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PluginArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repo", models.CharField(max_length=200)),
                ("commit_sha", models.CharField(max_length=40)),
                ("subdir", models.CharField(blank=True, default="", max_length=300)),
                ("plugin_name", models.CharField(max_length=128)),
                ("version", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, default="")),
                ("sha256", models.CharField(max_length=64)),
                ("size_bytes", models.PositiveIntegerField()),
                ("content", models.BinaryField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["repo", "-created_at"], name="plugin_archive_latest"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("repo", "commit_sha"), name="plugin_archive_repo_commit"
                    )
                ],
            },
        ),
    ]
